Map<String, String> hymns = {
  'A MIGHTY FORTRESS IS OUR GOD':
      'A mighty fortress is our God a bulwark never failing;\nOur helper He, amid the flood of mortal ills prevailing: For still our ancient foe doth seek to work us woe;\nHis craft and power are great, and, armed with cruel hate, On earth is not his equal. \n\nDid we in our own strength confide, our striving would be losing;\nWere not the right Man on our side, the Man of God\’s own choosing: Dost ask who that may be? Christ Jesus, it is He;\nLord Sabaoth, His Name, from age to age the same, And He must win the battle. \n\nAnd though this world, with devils filled, should threaten to undo us, We will not fear, for God hath willed His truth to triumph through us: The Prince of Darkness grim, we tremble not for him;\nHis rage we can endure, for lo, his doom is sure, One little word shall fell him. \n\nThat word above all earthly powers, no thanks to them, abideth;\nThe Spirit and the gifts are ours through Him Who with us sideth: Let goods and kindred go, this mortal life also;\nThe body they may kill: God\’s truth abideth still, His kingdom is forever.',
  'ABIDE WITH ME':
      'Abide with me;\nFast falls the eventide;\nThe darkness deepens;\nLord, with me abide: When other helpers fail, And comforts flee, Help of the helpless, O abide with me! \n\nSwift to its close ebbs Out life\’s little day;\nEarth\’s joys grow dim, Its glories pass away;\nChange and decay In all around I see: O Thou who changest not, Abide with me! \n\nI need Thy presence Ev\’ry passing hour;\nWhat but Thy grace can Foil the tempter\’s pow\’r? Who like Thyself My guide and stay can be? Thro\’ cloud and sunshine, O abide with me!',
  'ALAS AND DID MY SAVIOR BLEED':
      'Alas! and did my Savior bleed, And did my Sovereign die! Would he devote that sacred head For sinners such as I? \n\nWas it for crimes that I have done, He groaned upon the tree? Amazing pity! Grace unknown! And love beyond degree! \n\nWell might the sun in darkness hide, And shut its glories in, When God, the mighty maker, died For man, the creature\'s, sin \n\nThus might I hide my blushing face While his dear cross appears;\nDissolve my heart in thankfulness, And melt mine eyes to tears \n\nBut drops of tears can ne\'er repay The debt of love I owe. Here, Lord, I give myself away;\n\'Tis all that I can do',
  'ALL THE WAY MY SAVIOR LEADS ME':
      'All the way my Savior leads me;\nWhat have I to ask beside? Can I doubt His tender mercy, Who thro\’ life has been my guide? Heav\’nly peace, divinest comfort, Here by faith in Him to dwell! For I know whate\’er befall me, Jesus doeth all things well;\nFor I know whate\’er befall me, Jesus doeth all things well. \n\nAll the way my Savior leads me;\nCheers each winding path I tread, Gives me grace for ev\’ry trial, Feeds me with the living bread;\nTho\’ my weary steps may falter, And my soul athirst may be, Gushing from the Rock before me, Lo! A spring of joy I see;\nGushing from the Rock before me, Lo! A spring of joy I see;\n\n\nAll the way my Savior leads me;\nOh, the fullness of His love! Perfect rest to me is promised In my Father\’s house above: When my spirit, clothed immortal, Wings its flight to realms of day, This my song thro\’ endless ages: Jesus led me all the way;\nThis my song thro\’ endless ages: Jesus led me all the way;',
  'AMAZING GRACE':
      'Amazing grace! How sweet the sound, That saved a wretch like me! I once was lost, but now am found, Was blind, but now I see. \n\n‘Twas grace that taught my heart to fear, And grace my fears relieved;\nHow precious did that grace appear The hour I first believed! \n\nThro\’ many dangers, toils, and snares, I have already come;\n‘Tis grace hath bro\’t me safe thus far, And grace will lead me home. \n\nThe Lord has promised good to me, His word my hope secures;\nHe will my shield and portion be As long as life endures. \n\nWhen we\’ve been there ten thousand years, Bright shining as the sun, We\’ve no less days to sing God\’s praise Than when we first begun. ',
  'AND CAN IT BE':
      'And can it be that I should gain An int\’rest in the Savior\’s blood? Died He for me, who caused His pain? For me, who Him to earth pursued? Amazing love! how can it be That Thou, my God, should die for me? \n\nAmazing love! how can it be That Thou, my God, should die for me! \n\nHe left His Father\’s throne above, So free, so infinite His grace;\nEmptied Himself of all but love, And bled for Adam\’s helpless race;\n‘Tis mercy all, immense and free;\nO praise, my God, it reaches me. \n\nLong my imprisoned spirit lay Fast bound in sin and nature\’s night;\nThine eye diffused a quick\’ning ray, I woke, the dungeon flamed with light;\nMy chains fell off, my heart was free;\nI rose, went forth and followed Thee.',
  'ARE YOU WASHED IN THE BLOOD':
      'Have you been to Jesus For the cleansing pow\’r? Are you washed in the blood of the Lamb? Are you fully trusting in His grace this hour? Are you washed in the blood of the Lamb? \n\nAre you washed in the blood, In the soul cleansing blood of the Lamb? Are your garments spotless? Are they white as snow? Are you washed in the blood of the Lamb? \n\nAre you walking daily by the Savior\’s side? Are you washed in the blood of the Lamb? Do you rest each moment in the Crucified? Are you washed in the blood of the Lamb? \n\nWhen the Bridegroom cometh Will your robes be white? Are you washed in the blood of the Lamb? Will your soul be ready For the mansions bright, And be washed in the blood of the Lamb? \n\nLay aside the garments That are stained with sin, And be washed in the blood of the Lamb;\nThere\’s a fountain flowing For the soul unclean, O be washed in the blood of the lamb!',
  'AT CALVARY':
      'Years I spent in vanity and pride, Caring not my Lord was crucified, Knowing not it was for me He died On Calvary. \n\nMercy there was great, and grace was free;\nPardon there was multiplied to me;\nThere my burdened soul found liberty At Calvary. \n\nBy God\’s Word at last my sin I learned;\nThen I trembled at the law I\’d spurned, Till my guilty soul imploring turned To Calvary. \n\nNow I\’ve giv\’n to Jesus ev\’rything, Now I gladly own Him as my King, Now my raptured soul can only sing Of Calvary. \'\n\nOh, the love that drew salvation\’s plan! Oh, the grace that bro\’t it down to man! Oh, the mighty gulf that God did span At Calvary.',
  'AT THE CROSS':
      'Alas! and did my Savior bleed And did my Sov\’reign die? Would He devote that sacred head For such a worm as I? \n\nAt the cross, at the cross where I first saw the light, And the burden of my heart rolled away, It was there by faith I received my sight, And now I am happy all the day! \n\nThy body slain, sweet Jesus, Thine— And bathed in its own blood— While the firm mark of wrath divine, His soul in anguish stood. \n\nWas it for crimes that I had done He groaned upon the tree? Amazing pity! grace unknown! And love beyond degree! \n\nWell might the sun in darkness hide And shut his glories in, When Christ, the mighty Maker died, For man the creature\’s sin. \n\nThus might I hide my blushing face While His dear cross appears, Dissolve my heart in thankfulness, And melt my eyes to tears. \n\nBut drops of grief can ne\’er repay The debt of love I owe: Here, Lord, I give myself away, \’Tis all that I can do.',
  'BE STILL MY SOUL':
      'Be still, my soul;\nthe Lord is on thy side;\nBear patiently the cross of grief or pain;\nLeave to thy God to order and provide;\nIn every change He faithful will remain. Be still, my soul: thy best, thy heavenly, Friend Through thorny ways leads to a joyful end. \n\nBe still, my soul;\nthy God doth undertake To guide the future as He has the past. Thy hope, thy confidence, let nothing shake;\nAll now mysterious shall be bright at last. Be still, my soul: the waves and winds still know His voice who ruled them while He dwelt below. \n\nBe still, my soul: though dearest friends depart And all is darkened in the vale of tears;\nThen shalt thou better know His love, His heart, Who comes to soothe thy sorrows and thy fears. \n\nBe still, my soul;\nthy Jesus can repay From His own fullness all He takes away. Be still, my soul;\nthe hour is hastening on When we shall be forever with the Lord, When disappointment, grief, and fear are gone, Sorrow forgot, love\'s purest joys restored. Be still, my soul;\nwhen change and tears are past, All safe and blessed we shall meet at last.',
  'BE THOU MY VISION':
      'Be thou my vision, O Lord of my heart;\nNaught be all else to me, save that Thou art: Thou my best thought, by day or by night, Waking or sleeping, Thy presence my light. \n\nBe Thou my wisdom, and Thou my true word;\nI ever with Thee and Thou with me, Lord: Thou my great Father, I Thy son, Thou in me dwelling, and I with Thee one. \n\nRiches I heed not or man\’s empty praise, Thou mine inheritance, now and always: Thou and Thou only, first in my heart, High King of heaven, my treasure Thou art. \n\nHigh King of heaven, my victory won, May I reach heaven\’s joys, O bright heaven\’s Sun! Heart of my own heart, whatever befall, Still be my vision, O Ruler of all',
  'BECAUSE HE LIVES':
      'God sent His Son, they called Him Jesus;\nHe came to love, heal, and forgive;\nHe lived and died to buy my pardon, An empty grave is there to prove my Savior lives. \n\nBecause He lives I can face tomorrow;\nBecause He lives all fear is gone;\nBecause I know He holds the future, And life is worth the living just because He lives. \n\nHow sweet to hold a newborn baby, And feel the pride, and joy He gives;\nBut greater still the calm assurance, This child can face uncertain days because He lives. \n\nAnd then one day I\’ll cross the river;\nI\’ll fight life\’s final war with pain;\nAnd then as death gives way to vict\’ry, I\’ll see the lights of glory and I\’ll know He lives.',
  'BEFORE THE THRONE OF GOD ABOVE':
      'Before the throne of God above, I have a strong and perfect plea, A great High Priest whose name is Love Who ever lives and pleads for me. My name is graven on His hands, My name is written on His heart;\nI know that while in heaven He stands No tongue can bid me thence depart. No tongue can bid me thence depart. \n\nWhen Satan tempts me to despair, And tells me of the guilt within, Upward I look and see Him there Who made an end of all my sin. Because the sinless Savior died, My sinful soul is counted free;\nFor God, the Just, is satisfied To look on Him and pardon me. To look on him and pardon me. \n\nBehold him there! The risen Lamb, My perfect, spotless Righteousness, The great unchangeable I AM, The King of glory and of grace! One with Himself I cannot die, My soul is purchased by His blood;\nMy life is hid with Christ on high, With Christ, my Savior and my God With Christ, my Savior and my God',
  'BENEATH THE CROSS OF JESUS':
      'Beneath the cross of Jesus I fain would take my stand, The shadow of a mighty rock Within a weary land;\nA home within the wilderness, A rest upon the way, From the burning of the noontide heat And the burden of the day. \n\nUpon that cross of Jesus Mine eye at times can see The very dying form of One Who suffered there for me;\nAnd from my smitten heart with tears Two wonders I confess, The wonders of His glorious love And my unworthiness. \n\nI take, O Cross, thy shadow For my abiding place;\nI ask no other sunshine than The sunshine of His face;\nContent to let the world go by, To know no gain or loss, My sinful self my only shame, My glory all the cross.',
  'BLESSED ASSURANCE, JESUS IS MINE':
      'Blessed assurance, Jesus is mine! Oh, what a foretaste of glory divine! Heir of salvation, purchase of God, Born of His Spirit, washed in His blood. \n\nThis is my story, this is my song, Praising my Savior all the day long;\nThis is my story, this is my song, Praising my Savior all the day long. \n\nPerfect submission, perfect delight, Visions of rapture now burst on my sight: Angels descending bring from above Echoes of mercy, whispers of love. \n\nPerfect submission, all is at rest, I in my Savior am happy and blest: Watching and waiting, looking above Filled with His goodness, lost in His love.',
  'BLESSED REDEEMER':
      'Up Calv\’ry\’s mountain one dreadful morn, Walked Christ my Savior, weary and worn;\nFacing for sinners death on the cross, That He might save them from endless loss. \n\nBlessed Redeemer! Precious Redeemer! Seems now I see Him on Calvary\’s tree;\nWounded and bleeding, for sinners pleading— Blind and unheeding—dying for me! \n\n“Father, forgive them!” thus did He pray, E\’en while His lifeblood flowed fast away;\nPraying for sinners while in such woe— No one but Jesus ever loved so. \n\nOh how I love Him, Savior and Friend, How can my praises ever find end! Thro\’ years unnumbered on heaven\’s shore, My tongue shall praise Him forevermore.',
  'BLESSED REDEEMER':
      'Up Calv\’ry\’s mountain one dreadful morn, Walked Christ my Savior, weary and worn;\nFacing for sinners death on the cross, That He might save them from endless loss. \n\nBlessed Redeemer! Precious Redeemer! Seems now I see Him on Calvary\’s tree;\nWounded and bleeding, for sinners pleading— Blind and unheeding—dying for me! \n\n“Father, forgive them!” thus did He pray, E\’en while His lifeblood flowed fast away;\nPraying for sinners while in such woe— No one but Jesus ever loved so. \n\nOh how I love Him, Savior and Friend, How can my praises ever find end! Thro\’ years unnumbered on heaven\’s shore, My tongue shall praise Him forevermore.',
  'BREATHE ON ME':
      'Holy Spirit, breathe on me, Until my heart is clean;\nLet sunshine fill its inmost part, With not a cloud between. \n\nBreathe on me, breathe on me, Holy Spirit, breathe on me;\nTake Thou my heart, cleanse ev\’ry part, Holy Spirit, breathe on me. \n\nHoly Spirit, breathe on me, My stubborn will subdue;\nTeach me in words of living flame What Christ would have me do. \n\nHoly Spirit, breathe on me, Fill me with pow\’r divine;\nKindle a flame of love and zeal Within this heart of mine. \n\nHoly Spirit, breathe on me, Till I am all Thine own, Until my will is lost in Thine, To live for Thee alone.',
  'CLOSE TO THEE':
      'Thou, my everlasting portion, More than friend or life to me;\nAll along my pilgrim journey, Savior, let me walk with Thee. Close to Thee, close to Thee, Close to Thee, close to Thee;\nAll along my pilgrim journey, Savior, let me walk with Thee. \n\nNot for ease or worldly pleasure, Nor for fame my pray\’r shall be;\nGladly will I toil and suffer, Only let me walk with Thee. Close to Thee, close to Thee, Close to Thee, close to Thee;\nGladly will I toil and suffer, Only let me walk with Thee. \n\nLead me thro\’ the vale of shadows, Bear me o\’er life\’s fitful sea;\nThen the gate of life eternal May I enter, Lord, with Thee. Close to Thee, close to Thee, Close to Thee, close to Thee. Then the gate of life eternal May I enter, Lord, with Thee.',
  'COME, THOU FOUNT OF EVERY BLESSING':
      'Come, thou Fount of every blessing, Tune my heart to sing thy grace;\nStreams of mercy, never ceasing, Call for songs of loudest praise. Teach me some melodious sonnet, Sung by flaming tongues above. Praise the mount! I\'m fixed upon it, Mount of thy redeeming love. \n\nHere I raise mine Ebenezer;\nHither by thy help I\'m come;\nAnd I hope, by thy good pleasure, Safely to arrive at home. Jesus sought me when a stranger, Wandering from the fold of God;\nHe, to rescue me from danger, Interposed his precious blood. \n\nO to grace how great a debtor Daily I\'m constrained to be! Let thy goodness, like a fetter, Bind my wandering heart to thee. Prone to wander, Lord, I feel it, Prone to leave the God I love;\nHere\'s my heart, O take and seal it, Seal it for thy courts above.',
  'COUNT YOUR BLESSINGS':
      'When upon life\’s billows you are tempest tossed, When you are discouraged, thinking all is lost, Count your many blessings, name them one by one, And it will surprise you what the Lord hath done. \n\nCount your blessings, name them one by one, Count your blessings, see what God hath done! Count your blessings, name them one by one, And it will surprise you what the Lord hath done. \n\nAre you ever burdened with a load of care? Does the cross seem heavy you are called to bear? Count your many blessings, every doubt will fly, And you will keep singing as the days go by. When you look at others with their lands and gold, Think that Christ has promised you His wealth untold;\nCount your many blessings. Wealth can never buy Your reward in heaven, nor your home on high. So, amid the conflict whether great or small, Do not be disheartened, God is over all;\nCount your many blessings, angels will attend, Help and comfort give you to your journey\’s end.',
  'CROWN HIM WITH MANY CROWNS':
      'Crown Him with many crowns, The Lamb upon His throne, Hark! How the heav\’nly anthem drowns All music but it\’s own: Awake, my soul, and sing Of Him who died for thee, And hail Him as the matchless King Thro\’ all eternity. \n\nCrown Him the Lord of life, Who triumphed o\’er the grave, And rose victorious in the strife For those He came to save;\nHis glories now we sing Who died, and rose on high, Who died eternal life to bring, And lives that death may die. \n\nCrown Him the Lord of peace, Whose pow\’r a scepter sways From pole to pole, that wars may cease, And all be pray\’r and praise: His reign shall know no end, And round His pierced feet Fair flow\’rs of paradise extend Their fragrance ever sweet. \n\nCrown Him the Lord of love;\nBehold His hands and side, Those wounds, yet visible above, In Beauty glorified: All hail, Redeemer, hail! For Thou hast died for me: Thy praise and glory shall not fail Thro\’out eternity.',
  'DAY BY DAY':
      'Day by day and with each passing moment, Strength I find to meet my trials here;\nTrusting in my Father\’s wise bestowment, I\’ve no cause for worry or for fear. He whose heart is kind beyond all measure Gives unto each day what He deems best Lovingly its part of pain and pleasure, Mingling toil with peace and rest. \n\nEvery day the Lord Himself is near me With a special mercy for each hour;\nAll my cares He fain would bear, and cheer me, He whose name is Counselor and Pow\’r. The protection of His child and treasure Is a charge that on Himself He laid;\n“As thy days, thy strength shall be in measure,” This the pledge to me He made. \n\nHelp me then in every tribulation So to trust Thy promises, O Lord, That I lose not faith\’s sweet consolation Offered me within Thy holy Word. Help me, Lord when toil and trouble meeting. E\’er to take, as from a father\’s hand, One by one, the days, the moments fleeting, Till I reach the promised land.',
  'FACE TO FACE WITH CHRIST MY SAVIOR':
      'Face to face with Christ, my Savior, Face to face—what will it be, When with rapture I behold Him, Jesus Christ Who died for me? \n\nFace to face I shall behold Him, Far beyond the starry sky;\nFace to face in all His glory, I shall see Him by and by! \n\nOnly faintly now I see Him, With the darkened veil between, But a blessed day is coming, When His glory shall be seen. \n\nWhat rejoicing in His presence, When are banished grief and pain;\nWhen the crooked ways are straightened, And the dark things shall be plain. \n\nFace to face—oh, blissful moment! Face to face—to see and know;\nFace to face with my Redeemer, Jesus Christ Who loves me so.',
  'FAIREST LORD JESUS':
      'Fairest Lord Jesus, Ruler of all nature, O Thou of God and man the Son, Thee will I cherish, Thee will I honor, Thou, my soul\’s glory, joy and crown. \n\nFair are the meadows, fairer still the woodlands, Robed in the blooming garb of spring;\nJesus is fairer, Jesus is purer, Who makes the woeful heart to sing. \n\nFair is the sunshine, fairer still the moonlight, And all the twinkling starry host;\nJesus shines brighter, Jesus shines purer Than all the angels heaven can boast. \n\nAll fairest beauty, heavenly and earthly, Wondrously, Jesus, is found in Thee;\nNone can be nearer, fairer or dearer, Than Thou, my Savior, art to me. \n\nBeautiful Savior! Lord of all the nations! Son of God and Son of Man! Glory and honor, praise, adoration, Now and forever more be Thine.',
  'FOOTSTEPS OF JESUS':
      'Sweetly, Lord, have we heard Thee calling, “Come, follow Me!” And we see where Thy footprints falling, Lead us to Thee. \n\nFootprints of Jesus That make the pathway glow;\nWe will follow the steps of Jesus Where\’er they go. \n\nTho\’ they lead o\’er the cold, dark mountains, Seeking His sheep, Or along by Siloam\’s fountains, Helping the weak. \n\nIf they lead thro\’ the temple holy, Preaching the Word, Or in homes of the poor and lowly, Serving the Lord. \n\nThen at last, when on high He sees us, Our journey done, We will rest where the steps of Jesus End at His throne.',
  'GRACE GREATER THAN OUR SIN':
      'Marvelous grace of our loving Lord, Grace that exceeds our sin and our guilt, Yonder on Calvary\’s mount outpoured, There where the blood of the Lamb was spilt. \n\nGrace, grace, God\’s grace, Grace that will pardon and cleanse within;\nGrace, grace, God\’s grace, Grace that is greater than all our sin. \n\nDark is the stain that we cannot hide, What can avail to wash it away? Look! There is flowing a crimson tide;\nWhiter than snow you may be today. \n\nMarvelous, infinite, matchless grace, Freely bestowed on all who believe;\nAll who are longing to see his face, Will you this moment His grace receive?',
  'GREAT IS THY FAITHFULNESS':
      'Great is Thy faithfulness, O God, my Father, There is no shadow of turning with Thee;\nThou changest not, Thy compassions, They fail not;\nAs Thou had been, Thou forever wilt be. \n\nGreat is Thy faithfulness! Great is Thy faithfulness! Morning by morning new mercies I see;\nAll I have needed, Thy hand hath provided;\nGreat is Thy faithfulness, Lord, unto me! \n\nSummer and winter, And springtime and harvest, Sun, moon, and stars in their courses above Join with all nature in manifold witness To Thy great faithfulness, mercy, and love. \n\nPardon for sin and a peace that endureth, Thine own dear presence To cheer and to guide;\nStrength for today And bright hope for tomorrow, Blessings all mine, with ten thousand beside!',
  'HAVE THINE OWN WAY, LORD':
      'Have Thine own way, Lord! Have Thine own way! Thou art the potter, I am the clay! Mold me and make me after Thy will, While I am waiting, yielded and still. \n\nHave Thine own way, Lord! Have Thine own way! Search me and try me, Master, today! Whiter than snow, Lord, wash me just now, As in Thy presence humbly I bow. \n\nHave Thine own way, Lord! Have Thine own way! Wounded and weary, help me, I pray! Power, all power surely is Thine! Touch me and heal me, Savior divine. \n\nHave Thine own way, Lord! Have Thine own way! Hold o\’er my being absolute sway! Fill with Thy Spirit Till all shall see Christ only, always, living in me.',
  'HE HIDETH MY SOUL':
      'A wonderful Savior is Jesus my Lord, A wonderful Savior to me;\nHe hideth my soul in the cleft of the rock, Where rivers of pleasure I see. \n\nHe hideth my soul in the cleft of the rock That shadows a dry, thirsty land;\nHe hideth my life in the depths of His love, And covers me there with His hand, And covers me there with His hand. \n\nA wonderful Savior is Jesus my Lord, He taketh my burden away;\nHe holdeth me up, and I shall not be moved, He giveth me strength as my day. \n\nWith numberless blessings Each moment He crowns, And filled with His fullness divine, I sing in my rapture, oh, glory to God For such a Redeemer as mine! \n\nWhen clothed in His brightness, Transported I rise To meet Him in clouds of the sky, His perfect salvation, His wonderful love I\’ll shout with the millions on high.',
  'HE LEADETH ME, O BLESSED THOUGHT':
      'He leadeth me, o blessed thought O words with heav\’nly comfort fraught! Whate\’er I do, where\’er I be Still \’tis God\’s hand that leadeth me. \n\nHe leadeth me, He leadeth me, By His own hand He leadeth me;\nHis faithful follower I would be, For by His hand He leadeth me. \n\nSometimes mid scenes of deepest gloom, Sometimes where Eden\’s bowers bloom, By waters still, over troubled sea, Still \’tis His hand that leadeth me. \n\nLord, I would place my hand in Thine, Nor ever murmur nor repine;\nContent, whatever lot I see, Since \’tis my God that leadeth me. \n\nAnd when my task on earth is done, When by Thy grace the vict\’ry\’s won, E\’en death\’s cold wave I will not flee, Since God through Jordan leadeth me.',
  'HEAVEN CAME DOWN':
      'Oh, what a wonderful, wonderful day Day I will never forget After I wandered in darkness away Jesus my savior I met O what a tender compassionate friend, He met the need of my heart, Shadows dispelling, with joy I am telling He made all the darkness depart. \n\nHeaven came down and glory filled my soul When at the cross the Savior made me whole My sins He washed away, And my night He turned to day, Heaven came down and glory filled my soul. \n\nBorn of the Spirit with life from above Into God\'s family divine, \n\nJustified fully through Calvary\'s love, O what a standing is mine! And the transaction so quickly was made When as a sinner I came, Took of the offer Of grace He did proffer, He saved me, O praise His dear name! \n\nNow I\'ve a hope that will surely endure After the passing of time, I have a future in heaven for sure, There in those mansions sublime;\nAnd it\'s because of that wonderful day When at the cross I believed;\nRiches eternal and blessing supernal From His precious hand I received.',
  'HIGHER GROUND':
      'I\’m pressing on the upward way, New heights I\’m gaining ev\’ry day;\nStill praying as I onward bound, “Lord, plant my feet on higher ground.” \n\nLord, lift me up and let me stand, By faith, on heaven\’s tableland, A higher plane than I have found;\nLord, plant my feet on higher ground. \n\nMy heart has no desire to stay Where doubts arise and fears dismay;\nThough some may dwell where these abound, My prayer, my aim is higher ground. \n\nI want to live above the world, Though Satan\’s darts at me are hurled;\nFor faith has caught the joyful sound, The song of saints on higher ground. \n\nI want to scale the utmost height And catch a gleam of glory bright;\nBut still I\’ll pray till heav\’n I\’ve found, “Lord, lead me on to higher ground.”',
  'HIS NAME IS WONDERFUL':
      'His Name is Wonderful His Name is Wonderful His Name is Wonderful Jesus My Lord \n\nHe is the Mighty King Master of everything His Name is Wonderful Jesus My Lord \n\nHe\’s the Great shepherd The Rock of All Ages Almighty God is He \n\nBow down before Him Love and adore Him His Name is Wonderful Jesus My Lord',
  'HOLY GROUND':
      'This is Holy ground, we\’re standing on Holy ground For the Lord is here and where he is, is Holy This is holy ground, were standing on Holy Ground For the Lord is here and where he is, is Holy \n\nThese are holy hands we\’re lifting up holy hands;\nHe works through these hands And so these hands are holy These are holy hands, He\’s given us holy hands;\n\n\nHe works through these hands. And so these hands are Holy. \n\nChorus: We are standing on Holy ground. And I know that these are angels all around Let us praise Jesus now We are standing in Your presence, on Holy ground. \n\nWe are standing in Your presence We are standing in Your presence We are standing in Your presence on Holy ground.',
  'HOLY, HOLY, HOLY':
      'Holy, holy, holy! Lord God Almighty! Early in the morning our song shall rise to Thee;\nHoly, holy, holy, merciful and mighty! God in three Persons, blessed Trinity! \n\nHoly, holy, holy! All the saints adore Thee, Casting down their golden crowns Around the glassy sea;\nCherubim and seraphim falling down before Thee, Who wert, and art, and evermore shalt be. \n\nHoly, holy, holy! Tho\’ the darkness hide Thee, Tho\’ the eye of sinful man Thy glory may not see;\nOnly Thou art holy;\nthere is none beside Thee, Perfect in pow\’r, in love, and purity. \n\nHoly, holy, holy! Lord God Almighty! All Thy works shall praise Thy name, In earth, and sky, and sea;\nHoly, holy, holy;\nmerciful and mighty! God in three Persons, blessed Trinity!',
  'HOW GREAT THOU ART':
      'O Lord my God! When I in awesome wonder Consider all the worlds Thy hands have made, I see the stars, I hear the rolling thunder, Thy pow\’r thro\’out the universe displayed. \n\nThen sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art! Then sings my soul, my Savior God, to Thee;\nHow great Thou art, how great Thou art! \n\nWhen thro\’ the woods and forest glades I wander, And hear the birds sing sweetly in the trees;\nWhen I look down from lofty mountain grandeur, And hear the brook and feel the gentle breeze: \n\nAnd when I think that God, His Son not sparing, Sent Him to die, I scarce can take it in;\nThat on the cross, my burden gladly bearing, He bled and died to take away my sin. \n\nWhen Christ shall come with shout of acclamation, And take me home, what joy shall fill my heart! Then I shall bow in humble adoration, And there proclaim, my God, how great Thou art!',
  'HOW HE LOVES YOU AND ME':
      'O how He loves you and me. O how He loves you and me;\nHe gave His life, what more could he give? O how He loves you;\nO how He loves me;\nO how He loves you and me! \n\nJesus to Calv\’ry did go, His love for mankind to show;\nWhat he did there brought hope from despair: O how He loves you;\nO how He loves me;\nO how He loves you and me!',
  'I AM RESOLVED':
      'I am resolved no longer to linger, Charmed by the world\’s delight;\nThings that are higher, things that are nobler, These have allured my sight. \n\nI will hasten to Him, Hasten so glad and free, Jesus, greatest, highest, I will come to Thee. \n\nI am resolved to go to the Savior, Leaving my sin and strife;\nHe is the true one, He is the just one, He hath the words of life. \n\nI am resolved to follow the Savior, Faithful and true each day;\nHeed what He say-eth, do what He will-eth, He is the living way. \n\nI am resolved to enter the kingdom, Leaving the paths of sin;\nFriends may oppose me, foes may beset me, Still will I enter in. \n\nI am resolved, and who will go with me? Come friends, without delay;\nTaught by the Bible, led by the Spirit, We\’ll walk the heav\’nly way.',
  'I AM THINE, O LORD':
      'I am Thine, O Lord, I have heard Thy voice, And it told Thy love to me;\nBut I long to rise in the arms of faith, And be closer drawn to Thee. \n\nDraw me nearer, nearer blessed Lord, To the cross where Thou hast died;\nDraw me nearer, nearer, nearer blessed Lord, To Thy precious, bleeding side. \n\nConsecrate me now to Thy service, Lord, By the pow\’r of grace divine;\nLet my soul look up with a steadfast hope, And my will be lost in Thine. \n\nO the pure delight of a single hour That before Thy throne I spend;\nWhen I kneel in prayer, And with Thee, my God, I commune as friend with friend! \n\nThere are depths of love that I cannot know Till I cross the narrow sea;\nThere are heights of joy that I may not reach Till I rest in peace with Thee.',
  'I GAVE MY LIFE FOR THEE':
      'I gave My life for thee, My precious blood I shed, That thou might\’st ransomed be, And quickened from the dead;\nI gave, I gave My life for thee, What hast thou giv\’n for Me? I gave, I gave My life for thee, What hast thou giv\’n for Me? \n\nMy Father\’s house of lights, My glory circled throne, I left, for earthly night, For wand\’rings sad and lone;\nI left, I left it all for thee, Hast thou left aught for Me? I left, I left it all for thee, Hast thou left aught for Me? \n\nI suffered much for thee, More than thy tongue can tell, Of bitt\’rest agony, to rescue thee from hell;\nI\’ve borne, I\’ve borne it all for thee, What hast thou borne for Me? I\’ve borne, I\’ve borne it all for thee, What hast thou borne for Me? \n\nAnd I have brought to thee, Down from My home above, Salvation full and free, My pardon and My love;\nI bring, I bring rich gifts to thee, What hast thou brought to Me? I bring, I bring rich gifts to thee, What hast thou brought to me?',
  'I HAVE DECIDED TO FOLLOW JESUS':
      'I have decided to follow Jesus;\nI have decided to follow Jesus;\nI have decided to follow Jesus;\nNo turning back, no turning back. \n\nTho\’ none go with me, I still will follow;\nTho\’ none go with me, I still will follow;\nTho\’ none go with me, I still will follow;\nNo turning back, no turning back. \n\nMy cross I\’ll carry, till I see Jesus;\nMy cross I\’ll carry, till I see Jesus;\nMy cross I\’ll carry, till I see Jesus;\nNo turning back, no turning back. \n\nThe world behind me, the cross before me;\nThe world behind me, the cross before me;\nThe world behind me, the cross before me;\nNo turning back, no turning back.',
  'I KNOW THAT MY REDEEMER LIVETH':
      'I know that my Redeemer liveth, And on the earth again shall stand;\nI know eternal life He giveth, That grace and pow\’r are in His hand. \n\nI know, I know that Jesus liveth, And on the earth again shall stand;\nI know, I know that life He giv-eth, That grace and pow\’r are in His hand. \n\nI know His promise never faileth, The word He speaks, it cannot die;\nTho\’ cruel death my flesh assaileth, Yet I shall see Him by and by. \n\nI know my mansion He prepareth, That where He is there I may be;\nO wondrous tho\’t, for me He careth, And He at last will come for me.',
  'I KNOW WHOM I HAVE BELIEVED':
      'I know not why God\’s wondrous grace To me He hath made known, Nor why, unworthy, Christ in love Redeemed me for His own. \n\nBut I know Whom I have believèd, And am persuaded that He is able To keep that which I\’ve committed Unto Him against that day. \n\nI know not how this saving faith To me He did impart, Nor how believing in His Word Wrought peace within my heart. \n\nI know not how the Spirit moves, Convincing us of sin, Revealing Jesus through the Word, Creating faith in Him. \n\nI know not what of good or ill May be reserved for me, Of weary ways or golden days, Before His face I see. \n\nI know not when my Lord may come, At night or noonday fair, Nor if I walk the vale with Him, Or meet Him in the air.',
  'I LOVE TO TELL THE STORY':
      'I love to tell the story of unseen things above, Of Jesus and His glory, of Jesus and His love: I love to tell the story because I know \’tis true;\nIt satisfies my longings as nothing else can do. \n\nI love to tell the story, \’Twill be my theme in glory To tell the old, old story of Jesus and His love. \n\nI love to tell the story;\n\’Tis pleasant to repeat What seems each time I tell it, more wonderfully sweet: I love to tell the story, for some have never heard The message of salvation from God\’s own holy Word. \n\nI love to tell the story;\nFor those who know it best Seem hungering and thirsting to hear it, like the rest: And when, in scenes of glory, I sing the new, new song, \’Twill be the old, old story that I have loved so long.',
  'I MUST TELL JESUS':
      'I must tell Jesus all of my trials, I cannot bear these burdens alone;\nIn my distress He kindly will help me, He ever loves and cares for His own. \n\nI must tell Jesus! I must tell Jesus! I cannot bear my burdens alone;\nI must tell Jesus! I must tell Jesus! Jesus can help me, Jesus alone. \n\nI must tell Jesus all of my troubles, He is a kind, compassionate Friend;\nIf I but ask Him He will deliver, Make of my troubles quickly an end. \n\nTempted and tried I need a great Savior, One who can help my burdens to bear;\nI must tell Jesus, I must tell Jesus: He all my cares and sorrows will share. \n\nWhat must I do when worldliness calls me? What must I do when tempted to sin? I must tell Jesus, and He will help me Over the world the vict\’ry to win.',
  'I NEED THEE EVERY HOUR':
      'I need Thee ev\’ry hour, Most gracious Lord;\nNo tender voice like Thine Can peace afford. \n\nI need Thee, O I need Thee;\nEv\’ry hour I need Thee! O bless me now, my Savior, I come to Thee. \n\nI need Thee ev\’ry hour, Stay Thou nearby;\nTemptations lose their pow\’r When Thou art nigh. \n\nI need Thee ev\’ry hour, In joy or pain;\nCome quickly and abide, Or life is vain. \n\nI need Thee ev\’ry hour, Teach me Thy will;\nThe promises so rich In me fulfill. \n\nI need Thee ev\’ry hour, Most Holy One;\nO make me Thine indeed, Thou blessed Son.',
  'I SAW THE CROSS OF JESUS':
      'I saw the cross of Jesus, when burdened with my sin;\nI sought the cross of Jesus, \n\nto give me peace within;\nI brought my soul to Jesus, He cleansed it in His blood;\nAnd in the cross of Jesus I found my peace with God. \n\nI love the cross of Jesus, it tells me what I am— A vile and guilty creature, saved only through the Lamb;\nNo righteousness nor merit, no beauty can I plead;\nYet in the cross I glory, my title there I read. \n\nI trust the cross of Jesus, \n\nin every trying hour, My sure and certain refuge, my never failing tower;\nIn every fear and conflict, I more than conqueror am;\nLiving, I\’m safe, or dying, through Christ, the risen Lamb. \n\nSafe in the cross of Jesus! There let my weary heart Still rest in peace unshaken, till with Him, ne\’er to part;\nAnd then in strains of glory I\’ll sing His wondrous power, Where sin can never enter, and death is known no more.',
  'I STAND AMAZED IN THE PRESENCE':
      'I stand amazed in the presence Of Jesus the Nazarene, And wonder how He could love me, A sinner, condemned, unclean. \n\nHow marvelous! how wonderful! And my song shall ever be;\nHow marvelous! how wonderful! Is my Savior\’s love for me! \n\nFor me it was in the garden He prayed, “Not my will, but Thine,” He had no tears for His own griefs, But sweatdrops of blood for mine. \n\nHe took my sins and my sorrows, He made them His very own;\nHe bore the burden of Calv\’ry, And suffered and died alone. \n\nWhen with the ransomed in glory His face I at last shall see, \’Twill be my joy thro\’ the ages To sing of His love for me.',
  'I SURRENDER ALL':
      'All to Jesus I surrender, All to Him I freely give;\nI will ever love and trust Him, In His presence daily live. \n\nI surrender all, I surrender all;\nAll to Thee, my blessed Savior, I surrender all. \n\nAll to Jesus I surrender, Make me, Savior, wholly Thine;\nLet me feel Thy Holy Spirit, Truly know that Thou art mine. \n\nAll to Jesus I surrender, Lord, I give myself to Thee;\nFill me with Thy love and power, Let Thy blessing fall on me.',
  'I\’D RATHER HAVE JESUS':
      'I\’d rather have Jesus than silver or gold;\nI\’d rather be His than have riches untold;\nI\’d rather have Jesus than houses or lands;\nI\’d rather be led by His nail-pierced hand \n\nThan to be the king of a vast domain, Or be held in sin\’s dread sway;\nI\’d rather have Jesus than anything This world affords today. \n\nI\’d rather have Jesus than men\’s applause;\nI\’d rather be faithful to His dear cause;\nI\’d rather have Jesus than worldwide fame;\nI\’d rather be true to His holy name \n\nHe\’s fairer than lilies of rarest bloom;\nHe\’s sweeter than honey from out the comb;\nHe\’s all that my hungering spirit needs;\nI\’d rather have Jesus and let Him lead',
  'I\’VE FOUND A FRIEND':
      'I\’ve found a Friend, O such a friend! Christ loved me ere I knew Him;\nHe drew me with the cords of love, And thus He bound me to Him;\nAnd round my heart still closely twine Those ties which naught can sever, For I am His, and He is mine, forever and forever. \n\nI\’ve found a Friend, O such a friend! He bled, He died to save me;\nAnd not alone the gift of life, But His own Self He gave me! Naught that I have mine own I call, I\’ll hold it for the Giver, My heart, my strength, my life, my all Are His, and His forever. \n\nI\’ve found a Friend, O such a friend! All pow\’r to Him is given, To guard me on my onward course, And bring me safe to heaven. The eternal glories gleam afar, To nerve my faint endeavor;\nSo now to watch, to work, to war, And then to rest forever. \n\nI\’ve found a Friend, O such a friend! So kind and true and tender, So wise a Counselor and Guide, so mighty a Defender! From Him who loves me now so well What power my soul can sever? Shall life or death, shall earth or hell? No! I am His forever.',
  'IN HIS TIME':
      'In His time, in His time;\nHe makes all things beautiful in His time. Lord, please show me ev\’ry day As You\’re teaching me Your way, That You do just what You say in Your time. \n\nIn Your time, in Your time;\nYou make all things beautiful in Your time. Lord, my life to You I bring;\nMay each song I have to sing Be to You a lovely thing in Your time.',
  'IN THE GARDEN':
      'I come to the garden alone, While the dew is still on the roses;\nAnd the voice I hear, falling on my ear, The Son of God discloses. \n\nAnd He walks with me, And He talks with me, And He tells me I am His own, And the joy we share as we tarry there, None other has ever known. \n\nHe speaks, and the sound of His voice Is so sweet the birds hush their singing;\nAnd the melody that He gave to me Within my heart is ringing. \n\nI\’d stay in the garden with Him Tho\’ the night around me be falling;\nBut He bids me go;\nthro\’ the voice of woe, His voice to me is calling.',
  'IT IS WELL WITH MY SOUL':
      'When peace, like a river, attendeth my way, When sorrows like sea billows roll;\nWhatever my lot, Thou hast taught me to say, It is well, it is well with my soul. \n\nIt is well (it is well) with my soul (with my soul), It is well, it is well with my soul. \n\nTho\’ Satan should buffet, tho\’ trials should come, Let this blest assurance control, That Christ has regarded my helpless estate, And hath shed His own blood for my soul. \n\nMy sin—oh, the bliss of this glorious tho\’t: My sin not in part, but the whole Is nailed to the cross and I bear it no more, Praise the Lord, praise the Lord, O my soul! \n\nAnd Lord, haste the day when the faith shall be sight, The clouds be rolled back as a scroll, The trump shall resound and the Lord shall descend, “Even so,” it is well with my soul. \n\nNo condemnation now I dread;\nJesus, and all in Him is mine! Alive in Him, my living Head, And clothed in righteousness divine, Bold I approach th\’eternal throne, And claim the crown, thro\’ Christ my own.',
  'JESUS IS ALL THE WORLD TO ME':
      'Jesus is all the world to me, My life, my joy, my all;\nHe is my strength from day to day, Without Him I would fall: When I am sad, to Him I go;\nNo other one can cheer me so;\nWhen I am sad, He makes me glad;\nHe\’s my friend. \n\nJesus is all the world to me, My friend in trials sore;\nI go to Him for blessings, And He gives them o\’er and o\’er: He sends the sunshine and the rain, He sends the harvest\’s golden grain;\nSunshine and rain, harvest of grain;\nHe\’s my friend. \n\nJesus is all the world to me, And true to Him I\’ll be;\nOh, how could I this friend deny, When He\’s so true to me? Following Him, I know I\’m right, He watches o\’er me day and night;\nFollowing Him, by day and night;\nHe\’s my friend. \n\nJesus is all the world to me, I want no better friend;\nI trust Him now, I\’ll trust Him when Life\’s fleeting days shall end: Beautiful life with such a friend, Beautiful life that has no end;\nEternal life, eternal joy;\nHe\’s my friend.',
  'JESUS KEEP ME NEAR THE CROSS':
      'Jesus keep me near the cross, There a precious fountain, Free to all, a healing stream, Flows from Calv\’ry\’s mountain. \n\nIn the cross, in the cross, Be my glory ever, Till my ransomed soul shall find Rest beyond the river. \n\nNear the cross, a trembling soul, Love and mercy found me;\nThere the Bright and Morning Star Shed His beams around me. \n\nNear the cross! O lamb of God, Bring its scenes before me;\nHelp me walk from day to day With its shadow o\’er me. \n\nNear the cross! I\’ll watch and wait, Hoping, trusting ever, Till I reach the golden strand, Just beyond the river.',
  'JESUS, LOVER OF MY SOUL':
      'Jesus, lover of my soul, let me to Thy bosom fly, While the nearer waters roll, While the tempest still is high. Hide me, O my Savior, hide, Till the storm of life is past;\nSafe into the haven guide;\nOh, receive my soul at last. \n\nOther refuge have I none, Hangs my helpless soul on Thee;\nLeave, ah! leave me not alone, Still support and comfort me. All my trust on Thee is stayed, All my help from Thee I bring;\nCover my defenseless head with the shadow of Thy wing. \n\nWilt Thou not regard my call? Wilt Thou not accept my prayer? Lo! I sink, I faint, I fall— Lo! on Thee I cast my care. Reach me out Thy gracious hand! While I of Thy strength receive, Hoping against hope I stand, Dying, and behold, I live. \n\nThou, O Christ, art all I want, More than all in Thee I find;\nRaise the fallen, cheer the faint, Heal the sick, and lead the blind. Just and holy is Thy Name, Source of all true righteousness;\nThou art evermore the same, Thou art full of truth and grace. \n\nPlenteous grace with Thee is found, Grace to cover all my sin;\nLet the healing streams abound;\nMake and keep me pure within. Thou of life the fountain art, freely let me take of Thee;\nSpring Thou up within my heart;\nRise to all eternity.',
  'JESUS PAID IT ALL':
      'I hear the Savior say, “Thy strength indeed is small, Child of weakness, watch and pray, Find in Me thine all in all.” \n\nJesus paid it all, All to Him I owe;\nSin has left a crimson stain, He washed it white as snow. \n\nLord, now indeed I find Thy pow\’r, and Thine alone, Can change the leper\’s spots And melt the heart of stone. \n\nFor nothing good have I Whereby Thy grace to claim;\nI\’ll wash my garments white In the blood of Calv\’ry\’s Lamb. \n\nAnd when, before the throne, I stand in Him complete, “Jesus died my soul to save,” My lips shall still repeat.',
  'JESUS, I MY CROSS HAVE TAKEN':
      'Jesus, I my cross have taken, All to leave, and follow Thee;\nDestitute, despised, forsaken, Thou, from hence, my all shall be;\nPerish ev\’ry fond ambition, All I\’ve sought or hoped or known;\nYet how rich is my condition: God and heav\’n are still my own! \n\nLet the world despise and leave me, They have left my Savior, too;\nHuman hearts and looks deceive me, Thou art not, like man, untrue;\nAnd, while Thou shalt smile upon me, God of wisdom, love, and might, Foes may hate, and friends may shun me: Show Thy face, and all is bright. \n\nHaste thee on from grace to glory, Armed by faith, and winged by prayer;\nHeav\’n\’s eternal days before thee, God\’s own hand shall guide thee there;\nSoon shall close thy early mission, Swift shall pass thy pilgrim days;\nHope shall change to glad fruition, Faith to sight and prayer to praise',
  'JESUS, THY BOUNDLESS LOVE TO ME':
      'Jesus, Thy boundless love to me No thought can reach no tongue declare;\nUnite my thankful heart to Thee, And reign with-out a rival there! Thine wholly, Thine alone, I am;\nBe Thou alone my constant flame. \n\nO, grant that nothing in my soul May dwell, but Thy pure love alone;\nOh, may Thy love possess me whole, My joy, my treasure, and my crown! All coldness from my heart remove;\nMy every act, word, thought, be love. \n\nThis love unwearied I pursue And dauntlessly to Thee aspire. Oh, may Thy love my hope renew, Burn in my soul like heavenly fire! And day and night, be all my care To guard this sacred treasure there. \n\nIn suffering be Thy love my peace, In weakness by Thy love my power;\nAnd when the storms of life shall cease, O Jesus, in that final hour, Be Thou my rod and staff and guide And draw me safely to Thy side!',
  'JOYFUL, JOYFUL, WE ADORE THEE':
      'Joyful, joyful, we adore Thee, God of glory, Lord of love;\nHearts unfold like flow\’rs before Thee, Op\’ning to the sun above. Melt the clouds of sin and sadness;\nDrive the dark of doubt away;\nGiver of immortal gladness, Fill us with the light of day! \n\nAll Thy works with joy surround Thee, Earth and heav\’n reflect Thy rays, Stars and angels sing around Thee, Center of unbroken praise. Field and forest, vale and mountain, Flow\’ry meadow, flashing sea, Singing bird and flowing fountain Call us to rejoice in Thee. \n\nThou art giving and forgiving, Ever blessing, ever blest, Wellspring of the joy of living, Ocean depth of happy rest! Thou our Father, Christ our Brother – All who live in love are Thine;\nTeach us how to love each other, Lift us to the joy divine.',
  'JUST A CLOSER WALK WITH THEE':
      'I am weak, but Thou art strong;\nJesus, keep me from all wrong;\nI\’ll be satisfied as long As I walk, let me walk close to Thee. Just a closer walk with Thee, Grant it, Jesus, is my plea, Daily walking close to Thee, Let it be, dear Lord, let it be. Through this world of toil and snares, If I falter, Lord, who cares? Who with me my burden shares? None but Thee, dear Lord, none but Thee. When my feeble life is o\’er, Time for me will be no more;\nGuide me gently, safely o\’er To Thy kingdom shore, to Thy shore.',
  'JUST AS I AM':
      'Just as I am, without one plea, But that Thy blood was shed for me, And that Thou bidd\’st me come to Thee, O Lamb of God, I come! I come! \n\nJust as I am, and waiting not To rid my soul of one dark blot, To Thee whose blood can cleanse each spot, O Lamb of God, I come! I come! \n\nJust as I am, tho\’ tossed about With many a conflict, many a doubt, Fightings within and fears without, O Lamb of God, I come! I come! \n\nJust as I am, poor, wretched, blind;\nSight, riches, healing of the mind, Yea, all I need in Thee to find, O Lamb of God, I come! I come! \n\nJust as I am, Thou wilt receive, Wilt welcome, pardon, cleanse, relieve, Because Thy promise I believe, O Lamb of God, I come! I come! \n\nJust as I am, Thy love unknown Hath broken ev\’ry barrier down;\nNow to be Thine, yea, Thine alone, O Lamb of God, I come! I come! ',
  'LEANING ON THE EVERLASTING ARMS':
      'What a fellowship, what a joy divine, Leaning on the everlasting arms;\nWhat a blessedness, what a peace is mine,Leaning on the everlasting arms. Leaning, leaning, safe and secure from all alarms;\nLeaning, leaning, \n\nleaning on the everlasting arms.O how sweet to walk in this pilgrim way, Leaning on the everlasting arms;\nO how bright the path grows from day to day, Leaning on the everlasting arms. What have I to dread, what have I to fear, Leaning on the everlasting arms;\nI have blessed peace with my Lord so near, Leaning on the everlasting arms.',
  'LET JESUS COME INTO YOUR HEART':
      'If you are tired of the load of your sin, Let Jesus come into your heart;\nIf you desire a new life to begin, \n\nLet Jesus come into your heart. Just now, your doubtings give o\’er;\nJust now, reject Him no more;\nJust now, throw open the door;\nLet Jesus come into your heart. \n\nIf it\’s for purity now that you sigh, Let Jesus come into your heart;\nFountains for cleansing are flowing nearby, \n\nIf there\’s a tempest your voice cannot still, Let Jesus come into your heart;\nIf there\’s a void this world never can fill, \n\nIf you would join the glad songs of the blest, Let Jesus come into your heart;\nIf you would enter the mansions of rest,',
  'LET OTHERS SEE JESUS IN YOU':
      'While passing through this world of sin, And others your life shall view, Be clean and pure without, within, Let others see Jesus in you. \n\nLet others see Jesus in you, Let others see Jesus in you, Keep telling the story, be faithful and true, Let others see Jesus in you. \n\nYour life\’s a book before their eyes, They\’re reading it through and through;\nSay, does it point them to the skies, Do others see Jesus in you? \n\nWhat joy \’twill be at set of sun, In mansions beyond the blue, To find some souls that you have won;\nLet others see Jesus in you. \n\nThen live for Christ both day and night, Be faithful, be brave, and true, And lead the lost to life and light;\nLet others see Jesus in you.',
  'LET YOUR HEART BE BROKEN':
      'Let your heart be broken for a world in need— Feed the mouths that hunger, Soothe the wounds that bleed, Give the cup of water and the loaf of bread— Be the hands of Jesus, serving in His stead. \n\nHere on earth applying principles of love— Visible expression God still rules above, Living illustration of the Living Word, To the minds of all who\’ve never seen and heard. \n\nAdd to your believing deeds that prove it true— Knowing Christ as Savior, make Him Master, too: Follow in His footsteps, go where He has trod, In the world\’s great trouble risk yourself for God. \n\nLet your heart be tender and your vision clear— See mankind as God sees, serve Him far and near;\nLet your heart be broken by another\’s pain, Share your rich resources— give and give again.',
  'LIVING FOR JESUS':
      'Living for Jesus a life that is true, Striving to please Him in all that I do;\nYielding allegiance, glad-hearted and free, This is the pathway of blessing for me. \n\nO Jesus, Lord and Savior, \n\nI give myself to Thee;\nFor Thou, in Thine atonement, Didst give Thyself for me;\nI own no other Master, My heart shall be Thy throne;\nMy life I give, henceforth to live, O Christ, for Thee alone. \n\nLiving for Jesus who died in my place, Bearing on Calv\’ry my sin and disgrace;\nSuch love constrains me to answer His call, Follow His leading, and give Him my all. \n\nLiving for Jesus thro\’ earth\’s little while, My dearest treasure, the light of His smile;\nSeeking the lost ones He died to redeem, Bringing the weary to find rest in Him.',
  'LORD, I\’M COMING HOME':
      'I\’ve wandered far away from God, Now I\’m coming home;\nThe paths of sin too long I\’ve trod, Lord, I\’m coming home. \n\nComing home, coming home, Nevermore to roam, Open wide Thine arms of love, Lord I\’m coming home. \n\nI\’ve wasted many precious years, Now I\’m coming home;\nI now repent with bitter tears, Lord, I\’m coming home. \n\nI\’ve tired of sin and straying, Lord, Now I\’m coming home;\nI\’ll trust Thy love, believe Thy word, Lord, I\’m coming home. \n\nMy soul is sick, my heart is sore, Now I\’m coming home;\nMy strength renew, my hope restore, Lord, I\’m coming home.',
  'LOVE LIFTED ME':
      'I was sinking deep in sin, far from the peaceful shore, Very deeply stained within, sinking to rise no more;\nBut the Master of the sea heard my despairing cry, From the waters lifted me, now safe am I. \n\nLove lifted me! Love lifted me! When nothing else could help, Love lifted me. (repeat) \n\nAll my heart to Him I give, ever to Him I\’ll cling, In His blessed presence live, ever His praises sing;\nLove so mighty and so true merits my soul\’s best songs;\nFaithful loving service, too, to Him belongs. \n\nSouls in danger, look above, Jesus completely saves;\nHe will lift you by His love out of the angry waves;\nHe\’s the Master of the sea, billows His will obey;\nHe your Savior wants to be, be saved today.',
  'MAJESTIC SWEETNESS SITS ENTHRONED':
      'Majestic sweetness sits enthroned Upon the Savior\’s brow;\nHis head with radiant glories crowned, His lips with grace o\’erflow, His lips with grace o\’erflow. \n\nNo mortal can with Him compare, Among the sons of men;\nFairer is He than all the fair Who fill the heav\’nly train, Who fill the heav\’nly train. \n\nHe saw me plunged in deep distress, And flew to my relief;\nFor me He bore the shameful cross, And carried all my grief, And carried all my grief. \n\nTo Him I owe my life and breath, And all the joys I have;\nHe makes me triumph over death, And saves me from the grave, And saves me from the grave.',
  'MAKE ME A BLESSING':
      'Out in the highways and byways of life, Many are weary and sad;\nCarry the sunshine where darkness is rife, Making the sorrowing glad. \n\nMake me a blessing, Make me a blessing, Out of my life may Jesus shine;\nMake me a blessing, O Savior, I pray, Make me a blessing to someone today. \n\nTell the sweet story of Christ and His love, Tell of His pow\’r to forgive;\nOthers will trust Him if only you prove True, ev\’ry moment you live. \n\nGive as \’twas given to you in your need, Love as the Master loved you;\nBe to the helpless a helper indeed, Unto your mission be true.',
  'MOMENT BY MOMENT':
      'Dying with Jesus, by death reckoned mine;\nLiving with Jesus, a new life divine;\nLooking to Jesus till glory doth shine, Moment by moment, O Lord, I am Thine. \n\nMoment by moment I\’m kept in His love, Moment by moment I\’ve life from above;\nLooking to Jesus till glory doth shine;\nMoment by moment, O Lord, I am Thine. \n\nNever a trial that He is not there, Never a burden that He doth not bear, Never a sorrow that He doth no share, Moment by moment, I\’m under His care. \n\nNever a weakness that He doth not feel, Never a sickness that He cannot heal;\nMoment by moment, in woe or in weal, Jesus my Savior abides with me still.',
  'MORE LOVE TO THEE, O CHRIST':
      'More love to Thee, O Christ, More love to Thee! Hear Thou the prayer I make On bended knee;\nThis is my earnest plea: \n\nMore love, O Christ, to Thee, More love to Thee, More love to Thee! \n\nOnce earthly joy I craved, Sought peace and rest;\nNow Thee alone I seek, Give what is best;\nThis all my prayer shall be: \n\nThen shall my latest breath Whisper Thy praise;\nThis be the parting cry My heart shall raise;\nThis still its prayer shall be:',
  'MY FAITH HAS FOUND A RESTING PLACE':
      'My faith has found a resting place, Not in device nor creed;\nI trust the Everliving One, His wounds for me shall plead. \n\nI need no other argument, I need no other plea, It is enough that Jesus died, And that He died for me. \n\nEnough for me that Jesus saves, This ends my fear and doubt;\nA sinful soul I come to Him, He\’ll never cast me out. \n\nMy heart is leaning on the Word, The living Word of God, Salvation by my Savior\’s name, Salvation thro\’ His blood. \n\nMy great Physician heals the sick, The lost He came to save;\nFor me His precious blood He shed, For me His life he gave.',
  'MY JESUS, I LOVE THEE':
      'My Jesus, I love Thee, I know Thou are mine;\nFor Thee, all the follies of sin I resign;\nMy gracious Redeemer, my Savior art Thou;\nIf ever I loved Thee, my Jesus, \’tis now. \n\nI love Thee because Thou hast first loved me, And purchased my pardon on Calvary\’s tree;\nI love Thee for wearing the thorns on Thy brow;\nIf ever I loved Thee, my Jesus, \’tis now. \n\nI\’ll love Thee in life, I will love Thee in death, And praise Thee as long as Thou lendest me breath;\nAnd say, when the death dew lies cold on my brow;\nIf ever I loved Thee, my Jesus, \’tis now. \n\nIn mansions of glory and endless delight, I\’ll ever adore Thee in heaven so bright;\nAnd singing Thy praises, before Thee I\’ll bow;\nIf ever I loved Thee, my Jesus, \’tis now.',
  'MY SAVIOR FIRST OF ALL':
      'When my life work is ended, And I cross the swelling tide, When the bright and glorious morning I shall see;\nI shall know my Redeemer \n\nwhen I reach the other side, And His smile will be the first to welcome me. \n\nI shall know Him, I shall know Him, And redeemed by His side I shall stand, I shall know Him, I shall know Him, By the print of the nails in His hand. \n\nOh, the soul thrilling rapture When I view His blessed face, And the luster of His kindly beaming eye;\nHow my full heart will praise Him For the mercy, love and grace, That prepare for me a mansion in the sky. \n\nOh, the dear ones in glory, How they beckon me to come, And our parting at the river I recall;\nTo the sweet vales of Eden They will sing my welcome home;\nBut I long to meet my Savior first of all. \n\nThrough the gates to the city In a robe of spotless white, He will lead me where no tears will ever fall;\nIn the glad song of ages I shall mingle with delight;\nBut I long to meet my Savior first of all.',
  'MY TRIBUTE':
      'How can I say thanks for the things You have done for me Things so undeserved, Yet You give to prove Your love for me? The voices of a million angels Could not express my gratitude All that I am and ever hope to be, I owe it all to Thee. \n\nTo God be the glory, To God be the glory! To God be the glory For the things He has done. \n\nWith His blood He has saved me;\nWith His pow\’r He has raised me;\nTo God be the glory For the things He has done. \n\nJust let me live my life;\nLet it be pleasing Lord, to Thee. And should I gain any praise, Let it go to Calvary.',
  'NEAR TO THE HEART OF GOD':
      'There is a place of quiet rest, Near to the heart of God. A place where sin cannot molest, Near to the heart of God. \n\nO Jesus, blest Redeemer, Sent from the heart of God, Hold us who wait before Thee Near to the heart of God. \n\nThere is a place of comfort sweet, Near to the heart of God. A place where we our Savior meet, Near to the heart of God. \n\nThere is a place of full release, Near to the heart of God. A place where all is joy and peace, Near to the heart of God. \n\n',
  'NEARER, MY GOD, TO THEE':
      'Nearer, my God, to Thee, Nearer to Thee\nE\’en though it be a cross that raiseth me\nStill all my song shall be\nNearer, my God to Thee\nNearer, my God, to Thee, nearer to Thee\n\nThere let the way appear\nSteps unto heav\’n\nAll that Thou sendest me, In mercy giv\’n\nAngels to beckon me\nNearer, my God, to Thee\nNearer, my God, to Thee, nearer to Thee\n\nThen with my waking thoughts\nBright with Thy praise\nOut of my stony griefs Bethel I\’ll raise\nSo by my woes to be\nNearer, my God, to Thee\nNearer, my God, to Thee, nearer to Thee',
  'O COME ALL YE FAITHFUL':
      'O Come All Ye Faithful\nJoyful and triumphant,\nO come ye, O come ye to Bethlehem.\nCome and behold Him,\nBorn the King of Angels\n\nO come, let us adore Him,\nO come, let us adore Him,\nO come, let us adore Him,\nChrist the Lord.\n\nO Sing, choirs of angels,\nSing in exultation,\nSing all that hear in heaven God\'s holy word.\nGive to our Father glory in the Highest\n\nAll Hail! Lord, we greet Thee,\nBorn this happy morning,\nO Jesus! for evermore be Thy name adored.\nWord of the Father, now in flesh appearing',
  'O HOLY NIGHT':
      'O holy night! The stars are brightly shining, \nIt is the night of the dear Saviour\'s birth. \nLong lay the world in sin and error pining. \nTill He appeared and the Spirit felt its worth. \nA thrill of hope the weary world rejoices, \nFor yonder breaks a new and glorious morn. \nFall on your knees! Oh, hear the angel voices! \nO night divine, the night when Christ was born; \nO night, O holy night, O night divine! \nO night, O holy night, O night divine! \n\nTruly He taught us to love one another, \nHis law is love and His gospel is peace. \nChains he shall break, for the slave is our brother. \nAnd in his name all oppression shall cease. \nSweet hymns of joy in grateful chorus raise we, \nWith all our hearts we praise His holy name. \nChrist is the Lord! Then ever, ever praise we, \nHis power and glory ever more proclaim! \nHis power and glory ever more proclaim!',
  'O LITTLE TOWN OF BETHLEHEM':
      'O little town of Bethlehem\nHow still we see thee lie\nAbove thy deep and dreamless sleep\nThe silent stars go by\nYet in thy dark streets shineth\nThe everlasting Light\nThe hopes and fears of all the years\nAre met in thee tonight\n\nFor Christ is born of Mary\nAnd gathered all above\nWhile mortals sleep, the angels keep\nTheir watch of wondering love\nO morning stars together\nProclaim the holy birth\nAnd praises sing to God the King\nAnd Peace to men on earth\n\nHow silently, how silently\nThe wondrous gift is given!\nSo God imparts to human hearts\nThe blessings of His heaven.\nNo ear may his His coming,\nBut in this world of sin,\nWhere meek souls will receive him still,\nThe dear Christ enters in.\n\nO Holy Child of Bethlehem\nDescend to us, we pray\nCast out our sin and enter in\nBe born to us today\nWe hear the Christmas angels\nThe great glad tidings tell\nO come to us, abide with us\nOur Lord Emmanuel',
  'O COME O COME EMMANUEL':
      'O come, O come, Emmanuel\nAnd ransom captive Israel\nThat mourns in lonely exile here\nUntil the Son of God appear\nRejoice! Rejoice! Emmanuel\nShall come to thee, O Israel\n\nO come, Thou Rod of Jesse, free\nThine own from Satan\'s tyranny\nFrom depths of Hell Thy people save\nAnd give them victory o\'er the grave\nRejoice! Rejoice! Emmanuel\nShall come to thee, O Israel\n\nO come, Thou Day-Spring, come and cheer\nOur spirits by Thine advent here\nDisperse the gloomy clouds of night\nAnd death\'s dark shadows put to flight.\nRejoice! Rejoice! Emmanuel\nShall come to thee, O Israel',
  'O WORSHIP THE KING':
      'O worship the King, all glorious above\nAnd gratefully sing His wonderful love\nOur Shield and Defender, the Ancient of Days\nPavilioned in splendor, and girded with praise\n\nO tell of His might, O sing of His grace\nWhose robe is the light, whose canopy space\nHis chariots of wrath the deep thunderclouds form\nAnd dark is His path on the wings of the storm\n\nThy bountiful care what tongue can recite\nIt breathes in the air, it shines in the light\nIt streams from the hills, it descends to the plain\nAnd sweetly distills in the dew and the rain\n\nFrail children of dust, and feeble as frail\nIn Thee do we trust, nor find Thee to fail\nThy mercies how tender, how firm to the end\nOur Maker, Defender, Redeemer, and Friend',
  'THE OLD RUGGED CROSS':
      'On a hill far away stood an old rugged cross\nThe emblem of suff\’ring and shame\nAnd I love that old cross where the dearest and best\nFor a world of lost sinners was slain\n\nSo I\’ll cherish the old rugged cross\nTill my trophies at last I lay down\nI will cling to the old rugged cross\nAnd exchange it some day for a crown\n\nOh, that old rugged cross so despised by the world\nHas a wondrous attraction for me\nFor the dear Lamb of God left his glory above\nTo bear it to dark Calvary\n\nIn the old rugged cross stained with blood so divine\nSuch a wonderful beauty I see\nFor ‘twas on that old cross Jesus suffered and died\nTo pardon and sanctify me\n\nTo the old rugged cross I will ever be true\nIts shame and reproach gladly bear\nThen He\’ll call me some day to my home far away\nWhere His glory forever I\’ll share',
  'PASS ME NOT, O GENTLE SAVIOR':
      'Pass me not, O gentle Savior,\nHear my humble cry;\nWhile on others Thou art calling,\nDo not pass me by\n\nSavior, Savior,\nHear my humble cry;\nWhile on others Thou art calling,\nDo not pass me by\n\nLet me at Thy throne of mercy\nFind a sweet relief,\nKneeling there in deep contrition;\nHelp my unbelief\n\nTrusting only in Thy merit,\nWould I seek Thy face;\nHeal my wounded, broken spirit,\nSave me by Thy grace\n\nThou the spring of all my comfort,\nMore than life to me,\nWhom have I on earth beside Thee?\nWhom in heaven but Thee?',
  'PRAISE TO THE LORD, THE ALMIGHTY':
      'Praise to the Lord, the Almighty\nthe King of creation\nO my soul, praise Him\nfor He is thy health and salvation\nAll ye who hear, now to His temple draw near\nPraise Him in glad adoration\n\nPraise to the Lord\nwho over all things so wondrously reigneth\nShelters thee under His wings\nyea, so gently sustaineth\nHast thou not seen how thy\ndesires ever have been\nGranted in what He ordaineth\n\nPraise to the Lord\nwho doth prosper thy work and defend thee\nSurely His goodness and mercy\nhere daily attend thee\nPonder anew what the Almighty can do\nIf with His love He befriend thee\n\nPraise to the Lord\nO let all that is in me adore Him\nAll that hath life and breath\ncome now with praises before Him\nLet the Amen sound from His people again\nGladly for aye we adore Him',
  'ROCK OF AGES, CLEFT FOR ME':
      'Rock of Ages, cleft for me\nLet me hide myself in Thee\nLet the water and the blood\nFrom Thy wounded side which flowed\nBe of sin the double cure\nSave from wrath and make me pure\n\nNot the labors of my hands\nCan fulfill Thy law\’s demands\nCould my zeal no respite know,\nCould my tears forever flow,\nAll for sin could not atone;\nThou must save, and Thou alone\n\nWhile I draw this fleeting breath\nWhen mine eyes shall close in death\nWhen I soar to worlds unknown\nSee Thee on Thy judgment throne\nRock of Ages, cleft for me\nLet me hide myself in Thee',
  'SAVIOR, LIKE A SHEPHERD LEAD US':
      'Savior, like a shepherd lead us\nMuch we need Thy tender care\nIn Thy pleasant pastures feed us\nFor our use Thy folds prepare\nBlessed Jesus, blessed Jesus\nThou hast bought us, Thine we are\nBlessed Jesus, blessed Jesus\nThou hast bought us, Thine we are\n\nWe are Thine, do Thou befriend us\nBe the guardian of our way\nKeep Thy flock, from sin defend us\nSeek us when we go astray\nBlessed Jesus, blessed Jesus\nHear, O hear us when we pray\nBlessed Jesus, blessed Jesus\nHear, O hear us when we pray\n\nThou hast promised to receive us\nPoor and sinful though we be\nThou hast mercy to relieve us\nGrace to cleanse, and pow\’r to free\nBlessed Jesus, blessed Jesus\nEarly let us turn to Thee\nBlessed Jesus, blessed Jesus\nEarly let us turn to Thee',
  'SILENT NIGHT':
      'Silent night, holy night\nAll is calm, all is bright\nRound yon virgin mother and Child.\nHoly Infant, so tender and mild\nSleep in heavenly peace\nSleep in heavenly peace\n\nSilent night, holy night\nDarkness flies, all is light\nShepherds hear the angels sing\n“Alleluia! Hail the King\nChrist the Savior is born\nChrist the Savior is born”\n\nSilent night, holy night\nSon of God, love\’s pure light\nRadiant beams from Thy holy face\nWith the dawn of redeeming grace\nJesus, Lord, at Thy birth\nJesus, Lord, at Thy birth\n\nSilent night, holy night\nWondrous star, lend thy light\nWith the angels let us sing\nAlleluia to our King\nChrist the Savior is born\nChrist the Savior is bor',
  'SINCE JESUS CAME INTO MY HEART':
      'What a wonderful change \nIn my life has been wrought\nSince Jesus came into my heart!\nI have light in my soul for which long I had sought,\nSince Jesus came into my heart!\n\nSince Jesus came into my heart,\nSince Jesus came into my heart,\nFloods of joy o\’er my soul like the sea billows roll,\nSince Jesus came into my heart.\n\nI\’m possessed of a hope that is steadfast and sure,\nSince Jesus came into my heart!\nAnd no dark clouds of doubt \nNow my pathway obscure,\nSince Jesus came into my heart!\n\nThere\’s a light in the valley of death now for me,\nSince Jesus came into my heart!\nAnd the gates of the City beyond I can see,\nSince Jesus came into my heart!\n\nI shall go there to dwell in that City, I know,\nSince Jesus came into my heart!\nAnd I\’m happy, so happy, as onward I go,\nSince Jesus came into my heart!',
  'THE SOLID ROCK':
      'My hope is built on nothing less\nThan Jesus\’ blood and righteousness\nI dare not trust the sweetest frame\nBut wholly trust in Jesus\’ Name\n\nOn Christ the solid Rock I stand\nAll other ground is sinking sand\nAll other ground is sinking sand\n\nWhen darkness seems to hide His face\nI rest on His unchanging grace\nIn every high and stormy gale\nMy anchor holds within the veil\n\nWhen He shall come with trumpet sound\nOh may I then in Him be found\nDressed in His righteousness alone\nFaultless to stand before the throne',
  'THERE IS A FOUNTAIN':
      'There is a fountain filled with blood\nDrawn from Immanuel\’s veins\nAnd sinners, plunged beneath that flood\nLose all their guilty stains\nLose all their guilty stains, Lose all their guilty stains\nAnd sinners, plunged beneath that flood\nLose all their guilty stains\n\nThe dying thief rejoiced to see\nThat fountain in His day\nAnd there may I, though vile as he\nWash all my sins away\nWash all my sins away, Wash all my sins away\nAnd there may I, though vile as he\nWash all my sins away\n\nDear dying Lamb, Thy precious blood\nShall never lose its pow\’r\n‘Til all the ransomed church of God\nBe saved, to sin no more\nBe saved, to sin no more, Be saved, to sin no more\n‘Til all the ransomed church of God\nBe saved, to sin no more\n\nE\’er since by faith I saw the stream\nThy flowing wounds supply\nRedeeming love has been my theme\nAnd shall be ‘til I die\nAnd shall be ‘til I die, And shall be ‘til I die\nRedeeming love has been my theme\nAnd shall be ‘til I die',
  'THIS IS MY FATHER\’S WORLD':
      'This is my Father\’s world\nAnd to my list\’ning ears\nAll nature sings, and ‘round me rings\nThe music of the spheres\nThis is my Father\’s world\nI rest me in the thought\nOf rocks and trees, of skies and seas\nHis hand the wonders wrought\n\nThis is my Father\’s world\nThe birds their carols raise\nThe morning light, the lily white\nDeclare their Maker\’s praise\nThis is my Father\’s world\nHe shines in all that\’s fair\nIn the rustling grass I hear Him pass\nHe speaks to me everywhere\n\nThis is my Father\’s world\nO let me ne\’er forget\nThat though the wrong\nseems oft so strong\nGod is the ruler yet\nThis is my Father\’s world\nThe battle is not done\nJesus Who died shall be satisfied\nAnd earth and heaven be one',
  '\'TIS SO SWEET TO TRUST IN JESUS':
      '\'Tis so sweet to trust in Jesus\nJust to take Him at His word\nJust to rest upon His promise\nJust to know, "Thus saith the Lord"\n\nJesus, Jesus, how I trust Him\nHow I\'ve proved Him o\'er and o\'er\nJesus, Jesus, precious Jesus\nO for grace to trust Him more\n\nO how sweet to trust in Jesus\nJust to trust His cleansing blood\nJust in simple faith to plunge me\n‘Neath the healing, cleansing flood\n\nYes, \'tis sweet to trust in Jesus\nJust from sin and self to cease\nJust from Jesus simply taking\nLife and rest, and joy and peace\n\nI\'m so glad I learned to trust Him\nPrecious Jesus, Savior, Friend\nAnd I know that He is with me\nWill be with me to the end',
  'TRUST AND OBEY':
      'When we walk with the Lord\nIn the light of His Word\nWhat a glory He sheds on our way\nLet us do His good will\nHe abides with us still\nAnd with all who will trust and obey\n\nTrust and obey, for there\’s no other way\nTo be happy in Jesus, But to trust and obey\n\nNot a burden we bear, not a sorrow we share\nBut our toil He doth richly repay\nNot a grief or a loss\nNot a frown or a cross\nBut is blest if we trust and obey\n\nBut we never can prove the delights of His love\nUntil all on the altar we lay\nFor the favor He shows\nAnd the joy He bestows\nAre for them who will trust and obey\n\nThen in fellowship sweet we will sit at His feet\nOr we\’ll walk by His side in the way\nWhat He says we will do\nWhere He sends we will go\nNever fear, only trust and obe',
  'WHAT A FRIEND WE HAVE IN JESUS':
      'What a friend we have in Jesus\nAll our sins and griefs to bear\nWhat a privilege to carry\nEverything to God in prayer\nO what peace we often forfeit\nO what needless pain we bear\nAll because we do not carry\nEverything to God in prayer\n\nHave we trials and temptations\nIs there trouble anywhere\nWe should never be discouraged\nTake it to the Lord in prayer\nCan we find a friend so faithful\nWho will all our sorrows share\nJesus knows our every weakness\nTake it to the Lord in prayer\n\nAre we weak and heavy laden\nCumbered with a load of care\nPrecious Savior, still our refuge\nTake it to the Lord in prayer\nDo thy friends despise, forsake thee\nTake it to the Lord in prayer\nIn his arms he\'ll take and shield thee\nThou wilt find a solace there',
  'WHAT CHILD IS THIS':
      'What child is this, who, laid to rest\nOn Mary\'s lap, is sleeping?\nWhom angels greet with anthems sweet,\nWhile shepherds watch are keeping?\nThis, this is Christ the King,\nWhom shepherds guard and angels sing\nHaste, haste to bring him laud,\nThe Babe, the Son of Mary!\n\nSo bring Him incense, gold, and myrrh,\nCome peasant king to own Him,\nThe King of kings, salvation brings,\nLet loving hearts enthrone Him.\nRaise, raise the song on high,\nThe Virgin sings her lullaby\nJoy, joy, for Christ is born,\nThe Babe, the Son of Mary!'
};
