Map<String, String> hymns = {
  'A MIGHTY FORTRESS IS OUR GOD':
      'A mighty fortress is our God,\nA bulwark never failing;\nOur helper He, amid the flood\nOf mortal ills prevailing.\nFor still our ancient foe\nDoth seek to work us woe;\nHis craft and pow’r are great,\nAnd, armed with cruel hate,\nOn earth is not his equal.\n\nDid we in our own strength confide,\nOur striving would be losing;\nWere not the right Man on our side,\nThe Man of God’s own choosing.\nDost ask who that may be?\nChrist Jesus, it is He;\nLord Sabaoth, His name,\nFrom age to age the same,\nAnd He must win the battle.\n\nAnd tho’ this world, with devils filled,\nShould threaten to undo us,\nWe will not fear, for God hath willed\nHis truth to triumph thro’ us.\nThe Prince of Darkness grim—\nWe tremble not for him;\nHis rage we can endure,\nFor lo, his doom is sure,\nOne little word shall fell him.\n\nThat word above all earthly pow’rs,\nNo thanks to them, abideth;\nThe Spirit and the gifts are ours\nThro’ Him who with us sideth.\nLet goods and kindred go,\nThis mortal life also;\nThe body they may kill:\nGod’s truth abideth still,\nHis kingdom is forever.\n\n',
  'ABIDE WITH ME':
      'Abide with me: fast falls the eventide;\nThe darkness deepens; Lord, with me abide!\nWhen other helpers fail, and comforts flee,\nHelp of the helpless, O abide with me.\n\nSwift to its close ebbs out life’s little day;\nEarth’s joys grow dim, its glories pass away;\nChange and decay in all around I see:\nO Thou who changest not, abide with me.\n\nI need Thy presence ev’ry passing hour;\nWhat but Thy grace can foil the tempter’s pow’r?\nWho, like Thyself, my guide and stay can be?\nThrough cloud and sunshine, Lord, abide with me.\n\nI fear no foe, with Thee at hand to bless;\nIlls have no weight, and tears no bitterness:\nWhere is death’s sting? where, grave, thy victory?\nI triumph still, if Thou abide with me.\n\nHold Thou Thy cross before my closing eyes;\nShine through the gloom, and point me to the skies;\nHeav’n’s morning breaks, and earth’s vain shadows flee;\nIn life, in death, O Lord, abide with me.\n\n',
  'ALAS AND DID MY SAVIOR BLEED?':
      'Alas! and did my Savior bleed\nAnd did my Sovereign die?\nWould He devote that sacred head\nFor sinners such as I?\n\nRefrain\n\nAt the cross, at the cross where I first saw the light,\nAnd the burden of my heart rolled away,\nIt was there by faith I received my sight,\nAnd now I am happy all the day!\n\nThy body slain, sweet Jesus, Thine—\nAnd bathed in its own blood—\nWhile the firm mark of wrath divine,\nHis Soul in anguish stood.\n\nWas it for crimes that I had done\nHe groaned upon the tree?\nAmazing pity! grace unknown!\nAnd love beyond degree!\n\nWell might the sun in darkness hide\nAnd shut his glories in,\nWhen Christ, the mighty Maker died,\nFor man the creature’s sin.\n\nThus might I hide my blushing face\nWhile His dear cross appears,\nDissolve my heart in thankfulness,\nAnd melt my eyes to tears.\n\nBut drops of grief can ne’er repay\nThe debt of love I owe:\nHere, Lord, I give my self away\n’Tis all that I can do.\n\n',
  'ALL CREATURES OF OUR GOD AND KING':
      'All creatures of our God and King\nLift up your voice and with us sing,\nAlleluia! Alleluia!\nThou burning sun with golden beam,\nThou silver moon with softer gleam!\nRefrain\n\nO praise Him! O praise Him!\nAlleluia! Alleluia! Alleluia!\n\nThou rushing wind that art so strong\nYe clouds that sail in Heaven along,\nO praise Him! Alleluia!\nThou rising moon, in praise rejoice,\nYe lights of evening, find a voice!\n\nRefrain\n\nThou flowing water, pure and clear,\nMake music for thy Lord to hear,\nO praise Him! Alleluia!\nThou fire so masterful and bright,\nThat givest man both warmth and light.\n\nRefrain\n\nDear mother earth, who day by day\nUnfoldest blessings on our way,\nO praise Him! Alleluia!\nThe flowers and fruits that in thee grow,\nLet them His glory also show.\n\nRefrain\n\nAnd all ye men of tender heart,\nForgiving others, take your part,\nO sing ye! Alleluia!\nYe who long pain and sorrow bear,\nPraise God and on Him cast your care!\n\nRefrain\n\nAnd thou most kind and gentle Death,\nWaiting to hush our latest breath,\nO praise Him! Alleluia!\nThou leadest home the child of God,\nAnd Christ our Lord the way hath trod.\n\nRefrain\n\nLet all things their Creator bless,\nAnd worship Him in humbleness,\nO praise Him! Alleluia!\nPraise, praise the Father, praise the Son,\nAnd praise the Spirit, Three in One!\n\nRefrain\n\n',
  'ALL HAIL THE POWER OF JESUS’ NAME':
      'All hail the power of Jesus’ Name! Let angels prostrate fall;\nBring forth the royal diadem, and crown Him Lord of all.\nBring forth the royal diadem, and crown Him Lord of all.\nLet highborn seraphs tune the lyre, and as they tune it, fall\nBefore His face Who tunes their choir, and crown Him Lord of all.\nBefore His face Who tunes their choir, and crown Him Lord of all.\n\nCrown Him, ye morning stars of light, who fixed this floating ball;\nNow hail the strength of Israel’s might, and crown Him Lord of all.\nNow hail the strength of Israel’s might, and crown Him Lord of all.\n\nCrown Him, ye martyrs of your God, who from His altar call;\nExtol the Stem of Jesse’s Rod, and crown Him Lord of all.\nExtol the Stem of Jesse’s Rod, and crown Him Lord of all.\n\nYe seed of Israel’s chosen race, ye ransomed from the fall,\nHail Him Who saves you by His grace, and crown Him Lord of all.\nHail Him Who saves you by His grace, and crown Him Lord of all.\n\nHail Him, ye heirs of David’s line, whom David Lord did call,\nThe God incarnate, Man divine, and crown Him Lord of all,\nThe God incarnate, Man divine, and crown Him Lord of all.\n\nSinners, whose love can ne’er forget the wormwood and the gall,\nGo spread your trophies at His feet, and crown Him Lord of all.\nGo spread your trophies at His feet, and crown Him Lord of all.\n\nLet every tribe and every tongue before Him prostrate fall\nAnd shout in universal song the crownèd Lord of all.\nAnd shout in universal song the crownèd Lord of all.\n\n',
  'ALL THE WAY MY SAVIOR LEADS ME':
      'All the way my Savior leads me;\nWhat have I to ask beside?\nCan I doubt His tender mercy,\nWho through life has been my Guide?\nHeav’nly peace, divinest comfort,\nHere by faith in Him to dwell!\nFor I know, whate’er befall me,\nJesus doeth all things well;\nFor I know, whate’er befall me,\nJesus doeth all things well.\n\nAll the way my Savior leads me,\nCheers each winding path I tread;\nGives me grace for every trial,\nFeeds me with the living Bread.\nThough my weary steps may falter,\nAnd my soul athirst may be,\nGushing from the Rock before me,\nLo! A spring of joy I see;\nGushing from the Rock before me,\nLo! A spring of joy I see.\n\nAll the way my Savior leads me\nO the fullness of His love!\nPerfect rest to me is promised\nIn my Father’s house above.\nWhen my spirit, clothed immortal,\nWings its flight to realms of day\nThis my song through endless ages—\nJesus led me all the way;\nThis my song through endless ages—\nJesus led me all the way.\n\n',
  'AMAZING GRACE':
      'Amazing grace! how sweet the sound,\nThat saved a wretch like me!\nI once was lost, but now am found;\nWas blind, but now I see.\n\n’Twas grace that taught my heart to fear,\nAnd grace my fears relieved;\nHow precious did that grace appear\nThe hour I first believed!\n\nThro’ many dangers, toils and snares\nI have already come;\n’Tis grace has brought me safe thus far,\nAnd grace will lead me home.\n\nThe Lord has promised good to me;\nHis Word my hope secures;\nHe will my Shield and Portion be,\nAs long as life endures.\n\nThe earth shall soon dissolve like snow;\nThe sun forbear to shine;\nBut God, who called me here below,\nWill be forever mine.\n\nWhen we’ve been there ten thousand years,\nBright shining as the sun,\nWe’ve no less days to sing God’s praise\nThan when we’d first begun.\n\n',
  'AT CALVARY':
      'Years I spent in vanity and pride,\nCaring not my Lord was crucified,\nKnowing not it was for me He died on Calvary.\nRefrain\n\nMercy there was great, and grace was free;\nPardon there was multiplied to me;\nThere my burdened soul found liberty at Calvary.\n\nBy God’s Word at last my sin I learned;\nThen I trembled at the law I’d spurned,\nTill my guilty soul imploring turned to Calvary.\n\nRefrain\n\nNow I’ve given to Jesus everything,\nNow I gladly own Him as my King,\nNow my raptured soul can only sing of Calvary!\n\nRefrain\n\nOh, the love that drew salvation’s plan!\nOh, the grace that brought it down to man!\nOh, the mighty gulf that God did span at Calvary!\n\nRefrain\n\n',
  'BATTLE HYMN OF THE REPUBLIC':
      'Mine eyes have seen the glory of the coming of the Lord;\nHe is trampling out the vintage where the grapes of wrath are stored;\nHe hath loosed the fateful lightning of His terrible swift sword;\nHis truth is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! His truth is marching on.\n\nI have seen Him in the watch fires of a hundred circling camps\nThey have builded Him an altar in the evening dews and damps;\nI can read His righteous sentence by the dim and flaring lamps;\nHis day is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! His day is marching on.\n\nI have read a fiery Gospel writ in burnished rows of steel;\n“As ye deal with My contemners, so with you My grace shall deal”;\nLet the Hero, born of woman, crush the serpent with His heel,\nSince God is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! Since God is marching on.\n\nHe has sounded forth the trumpet that shall never call retreat;\nHe is sifting out the hearts of men before His judgment seat;\nOh, be swift, my soul, to answer Him! be jubilant, my feet;\nOur God is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! Our God is marching on.\n\nIn the beauty of the lilies Christ was born across the sea,\nWith a glory in His bosom that transfigures you and me:\nAs He died to make men holy, let us live to make men free;\nWhile God is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! While God is marching on.\n\nHe is coming like the glory of the morning on the wave,\nHe is wisdom to the mighty, He is honor to the brave;\nSo the world shall be His footstool, and the soul of wrong His slave,\nOur God is marching on.\nGlory! Glory! Hallelujah! Glory! Glory! Hallelujah!\nGlory! Glory! Hallelujah! Our God is marching on.\n \n',
  'BE THOU MY VISION':
      'Be Thou my Vision, O Lord of my heart;\nNaught be all else to me, save that Thou art;\nThou my best thought, by day or by night,\nWaking or sleeping, Thy presence my light.\n\nBe Thou my Wisdom, and Thou my true Word;\nI ever with Thee and Thou with me, Lord;\nThou my great Father, and I Thy true son,\nThou in me dwelling, and I with Thee one.\n\nRiches I heed not, nor man’s empty praise;\nThou mine inheritance, now and always;\nThou and Thou only, first in my heart,\nHigh King of heaven, my treasure Thou art.\n\nHigh King of heaven, my victory won,\nMay I reach heaven’s joys, O bright heav’n’s Sun!\nHeart of my own heart, whatever befall,\nStill be my Vision, O Ruler of all.\n\n',
  'BEFORE THE THRONE OF GOD ABOVE':
      'Before the throne of God above\nI have a strong and perfect plea.\nA great high Priest whose Name is Love\nWho ever lives and pleads for me.\nMy name is graven on His hands,\nMy name is written on His heart.\nI know that while in Heaven He stands\nNo tongue can bid me thence depart.\nWhen Satan tempts me to despair\nAnd tells me of the guilt within,\nUpward I look and see Him there\nWho made an end of all my sin.\nBecause the sinless Savior died\nMy sinful soul is counted free.\nFor God the just is satisfied\nTo look on Him and pardon me.\n\nBehold Him there the risen Lamb,\nMy perfect spotless righteousness,\nThe great unchangeable I AM,\nThe King of glory and of grace,\nOne in Himself I cannot die.\nMy soul is purchased by His blood,\nMy life is hid with Christ on high,\nWith Christ my Savior and my God!\n \n',
  'BLESSED ASSURANCE':
      'Blessèd assurance, Jesus is mine!\nO what a foretaste of glory divine!\nHeir of salvation, purchase of God,\nBorn of His Spirit, washed in His blood.\n\nRefrain\n\nThis is my story, this is my song,\nPraising my Savior, all the day long;\nThis is my story, this is my song,\nPraising my Savior, all the day long.\n\nPerfect submission, perfect delight,\nVisions of rapture now burst on my sight;\nAngels descending bring from above\nEchoes of mercy, whispers of love.\n\nRefrain\n\nPerfect submission, all is at rest\nI in my Savior am happy and blest,\nWatching and waiting, looking above,\nFilled with His goodness, lost in His love.\n\nRefrain\n \n',
  'BLEST BE THE TIE THAT BINDS':
      'Blest be the tie that binds\nOur hearts in Christian love;\nThe fellowship of kindred minds\nIs like to that above.\n\nBefore our Father’s throne\nWe pour our ardent prayers;\nOur fears, our hopes, our aims are one,\nOur comforts and our cares.\n\nWe share our mutual woes,\nOur mutual burdens bear;\nAnd often for each other flows\nThe sympathizing tear.\n\nWhen for a while we part,\nThis thought will soothe our pain,\nThat we shall still be joined in heart,\nAnd hope to meet again.\n\nThis glorious hope revives\nOur courage by the way,\nWhile each in expectation lives,\nAnd longs to see the day.\n\nFrom sorrow, toil, and pain,\nAnd sin we shall be free;\nAnd perfect love and friendship reign\nThro’ all eternity.\n\n',
  'A CHILD OF THE KING':
      'My Father is rich in houses and lands,\nHe holdeth the wealth of the world in His hands!\nOf rubies and diamonds, of silver and gold,\nHis coffers are full, He has riches untold.\n\nRefrain\n\nI’m a child of the King,\nA child of the King:\nWith Jesus my Savior,\nI’m a child of the King.\n\nMy Father’s own Son, the Savior of men,\nOnce wandered on earth as the poorest of them;\nBut now He is pleading our pardon on high,\nThat we may be His when He comes by and by.\n\nRefrain\n\nI once was an outcast stranger on earth,\nA sinner by choice, an alien by birth,\nBut I’ve been adopted, my name’s written down,\nAn heir to a mansion, a robe and a crown.\n\nRefrain\n\nA tent or a cottage, why should I care?\nThey’re building a palace for me over there;\nThough exiled from home, yet still may I sing:\nAll glory to God, I’m a child of the King.\n\nRefrain\n\n',
  'CHRIST THE LORD IS RISEN TODAY':
      'Christ, the Lord, is risen today, Alleluia!\nSons of men and angels say, Alleluia!\nRaise your joys and triumphs high, Alleluia!\nSing, ye heavens, and earth, reply, Alleluia!\nLove’s redeeming work is done, Alleluia!\nFought the fight, the battle won, Alleluia!\nLo! the Sun’s eclipse is over, Alleluia!\nLo! He sets in blood no more, Alleluia!\n\nVain the stone, the watch, the seal, Alleluia!\nChrist hath burst the gates of hell, Alleluia!\nDeath in vain forbids His rise, Alleluia!\nChrist hath opened paradise, Alleluia!\n\nLives again our glorious King, Alleluia!\nWhere, O death, is now thy sting? Alleluia!\nOnce He died our souls to save, Alleluia!\nWhere thy victory, O grave? Alleluia!\n\nSoar we now where Christ hath led, Alleluia!\nFollowing our exalted Head, Alleluia!\nMade like Him, like Him we rise, Alleluia!\nOurs the cross, the grave, the skies, Alleluia!\n\nHail, the Lord of earth and Heaven, Alleluia!\nPraise to Thee by both be given, Alleluia!\nThee we greet triumphant now, Alleluia!\nHail, the resurrection, thou, Alleluia!\n\nKing of glory, Soul of bliss, Alleluia!\nEverlasting life is this, Alleluia!\nThee to know, Thy power to prove, Alleluia!\nThus to sing and thus to love, Alleluia!\n\nHymns of praise then let us sing, Alleluia!\nUnto Christ, our heavenly King, Alleluia!\nWho endured the cross and grave, Alleluia!\nSinners to redeem and save. Alleluia!\n\nBut the pains that He endured, Alleluia!\nOur salvation have procured, Alleluia!\nNow above the sky He’s King, Alleluia!\nWhere the angels ever sing. Alleluia!\n\nJesus Christ is risen today, Alleluia!\nOur triumphant holy day, Alleluia!\nWho did once upon the cross, Alleluia!\nSuffer to redeem our loss. Alleluia!\n\n',
  'CLEANSE ME':
      'Search me, O God,\nAnd know my heart today;\nTry me, O Savior,\nKnow my thoughts, I pray.\nSee if there be\nSome wicked way in me;\nCleanse me from every sin\nAnd set me free.\nI praise Thee, Lord,\nFor cleansing me from sin;\nFulfill Thy Word,\nAnd make me pure within.\nFill me with fire\nWhere once I burned with shame;\nGrant my desire\nTo magnify Thy Name.\n\nLord, take my life,\nAnd make it wholly Thine;\nFill my poor heart\nWith Thy great love divine.\nTake all my will,\nMy passion, self and pride;\nI now surrender, Lord\nIn me abide.\n\nO Holy Ghost,\nRevival comes from Thee;\nSend a revival,\nStart the work in me.\nThy Word declares\nThou wilt supply our need;\nFor blessings now,\nO Lord, I humbly plead.\n\n',
  'COME THOU FOUNT OF EVERY BLESSING':
      'Come, Thou Fount of every blessing,\nTune my heart to sing Thy grace;\nStreams of mercy, never ceasing,\nCall for songs of loudest praise.\nTeach me some melodious sonnet,\nSung by flaming tongues above.\nPraise the mount! I’m fixed upon it,\nMount of Thy redeeming love.\nSorrowing I shall be in spirit,\nTill released from flesh and sin,\nYet from what I do inherit,\nHere Thy praises I’ll begin;\nHere I raise my Ebenezer;\nHere by Thy great help I’ve come;\nAnd I hope, by Thy good pleasure,\nSafely to arrive at home.\n\nJesus sought me when a stranger,\nWandering from the fold of God;\nHe, to rescue me from danger,\nInterposed His precious blood;\nHow His kindness yet pursues me\nMortal tongue can never tell,\nClothed in flesh, till death shall loose me\nI cannot proclaim it well.\n\nO to grace how great a debtor\nDaily I’m constrained to be!\nLet Thy goodness, like a fetter,\nBind my wandering heart to Thee.\nProne to wander, Lord, I feel it,\nProne to leave the God I love;\nHere’s my heart, O take and seal it,\nSeal it for Thy courts above.\n\nO that day when freed from sinning,\nI shall see Thy lovely face;\nClothed then in blood washed linen\nHow I’ll sing Thy sovereign grace;\nCome, my Lord, no longer tarry,\nTake my ransomed soul away;\nSend thine angels now to carry\nMe to realms of endless day.\n\n',
  'COUNT YOUR BLESSINGS':
      'When upon life’s billows you are tempest tossed,\nWhen you are discouraged, thinking all is lost,\nCount your many blessings, name them one by one,\nAnd it will surprise you what the Lord hath done.\nRefrain\n\nCount your blessings, name them one by one,\nCount your blessings, see what God hath done!\nCount your blessings, name them one by one,\nAnd it will surprise you what the Lord hath done.\n\nAre you ever burdened with a load of care?\nDoes the cross seem heavy you are called to bear?\nCount your many blessings, every doubt will fly,\nAnd you will keep singing as the days go by.\n\nRefrain\n\nWhen you look at others with their lands and gold,\nThink that Christ has promised you His wealth untold;\nCount your many blessings. Wealth can never buy\nYour reward in heaven, nor your home on high.\n\nRefrain\n\nSo, amid the conflict whether great or small,\nDo not be disheartened, God is over all;\nCount your many blessings, angels will attend,\nHelp and comfort give you to your journey’s end.\n\nRefrain\n\n',
  'CROWN HIM WITH MANY CROWNS':
      'Crown Him with many crowns, the Lamb upon His throne.\nHark! How the heavenly anthem drowns all music but its own.\nAwake, my soul, and sing of Him who died for thee,\nAnd hail Him as thy matchless King through all eternity.\n\nCrown Him the virgin’s Son, the God incarnate born,\nWhose arm those crimson trophies won which now His brow adorn;\nFruit of the mystic rose, as of that rose the stem;\nThe root whence mercy ever flows, the Babe of Bethlehem.\n\nCrown Him the Son of God, before the worlds began,\nAnd ye who tread where He hath trod, crown Him the Son of Man;\nWho every grief hath known that wrings the human breast,\nAnd takes and bears them for His own, that all in Him may rest.\n\nCrown Him the Lord of life, who triumphed over the grave,\nAnd rose victorious in the strife for those He came to save.\nHis glories now we sing, who died, and rose on high,\nWho died eternal life to bring, and lives that death may die.\n\nCrown Him the Lord of peace, whose power a scepter sways\nFrom pole to pole, that wars may cease, and all be prayer and praise.\nHis reign shall know no end, and round His piercèd feet\nFair flowers of paradise extend their fragrance ever sweet.\n\nCrown Him the Lord of love, behold His hands and side,\nThose wounds, yet visible above, in beauty glorified.\nNo angel in the sky can fully bear that sight,\nBut downward bends his burning eye at mysteries so bright.\n\nCrown Him the Lord of Heaven, enthroned in worlds above,\nCrown Him the King to Whom is given the wondrous name of Love.\nCrown Him with many crowns, as thrones before Him fall;\nCrown Him, ye kings, with many crowns, for He is King of all.\n\nCrown Him the Lord of lords, who over all doth reign,\nWho once on earth, the incarnate Word, for ransomed sinners slain,\nNow lives in realms of light, where saints with angels sing\nTheir songs before Him day and night, their God, Redeemer, King.\n\nCrown Him the Lord of years, the Potentate of time,\nCreator of the rolling spheres, ineffably sublime.\nAll hail, Redeemer, hail! For Thou has died for me;\nThy praise and glory shall not fail throughout eternity.\n\n',
  'DAY BY DAY':
      'Day by day, and with each passing moment,\nStrength I find, to meet my trials here;\nTrusting in my Father’s wise bestowment,\nI’ve no cause for worry or for fear.\nHe Whose heart is kind beyond all measure\nGives unto each day what He deems best—\nLovingly, its part of pain and pleasure,\nMingling toil with peace and rest.\n\nEvery day, the Lord Himself is near me\nWith a special mercy for each hour;\nAll my cares He fain would bear, and cheer me,\nHe Whose Name is Counselor and Power;\nThe protection of His child and treasure\nIs a charge that on Himself He laid;\n“As thy days, thy strength shall be in measure,”\nThis the pledge to me He made.\n\nHelp me then in every tribulation\nSo to trust Thy promises, O Lord,\nThat I lose not faith’s sweet consolation\nOffered me within Thy holy Word.\nHelp me, Lord, when toil and trouble meeting,\nEver to take, as from a father’s hand,\nOne by one, the days, the moments fleeting,\nTill I reach the promised land.\n\n',
  'DOXOLOGY':
      'Praise God, from Whom all blessings flow;\nPraise Him, all creatures here below;\nPraise Him above, ye heavenly host;\nPraise Father, Son, and Holy Ghost.\n\n',
  'ETERNAL FATHER STRONG TO SAVE':
      'Eternal Father, strong to save,\nWhose arm hath bound the restless wave,\nWho biddest the mighty ocean deep\nIts own appointed limits keep;\nOh, hear us when we cry to Thee,\nFor those in peril on the sea!\n\nO Christ! Whose voice the waters heard\nAnd hushed their raging at Thy Word,\nWho walked on the foaming deep,\nAnd calm amidst its rage didst sleep;\nOh, hear us when we cry to Thee,\nFor those in peril on the sea!\n\nMost Holy Spirit! Who didst brood\nUpon the chaos dark and rude,\nAnd bid its angry tumult cease,\nAnd give, for wild confusion, peace;\nOh, hear us when we cry to Thee,\nFor those in peril on the sea!\n\nO Trinity of love and power!\nOur family shield in danger’s hour;\nFrom rock and tempest, fire and foe,\nProtect us wheresoever we go;\nThus evermore shall rise to Thee\nGlad hymns of praise from land and sea.\n\n',
  'FACE TO FACE':
      'Face to face with Christ, my Saviour,\nFace to face— what will it be,\nWhen with rapture I behold Him,\nJesus Christ, who died for me?\n\nRefrain:\nFace to face I shall behold Him,\nFar beyond the starry sky;\nFace to face in all His glory,\nI shall see Him by and by!\n\nOnly faintly now I see Him,\nWith the darkling veil between;\nBut a blessed day is coming,\nWhen His glory shall be seen.\n\nWhat rejoicing in His presence,\nWhen are banished grief and pain;\nWhen the crooked ways are straightened,\nAnd the dark things shall be plain.\n\nFace to face! O blissful moment!\nFace to face— to see and know;\nFace to face with my Redeemer,\nJesus Christ, who loves me so.\n\n',
  'FAIREST LORD JESUS':
      'Fairest Lord Jesus! Ruler of all nature!\nO Thou of God and man the Son!\nThee will I cherish, Thee will I honor,\nThou, my soul’s glory, joy, and crown!\n\nFair are the meadows, Fairer still the woodlands,\nRobed in the blooming garb of spring:\nJesus is fairer, Jesus is purer,\nWho makes the woeful heart to sing.\n\nFair is the sunshine, Fairer still the moonlight,\nAnd all the twinkling starry host:\nJesus shines brighter, Jesus shines purer,\nThan all the angels heav’n can boast.\n\nBeautiful Saviour! Lord of the nations!\nSon of God and Son of Man!\nGlory and honor, Praise, adoration,\nNow and forevermore be Thine!\n\n',
  'FAITH IS THE VICTORY':
      'Encamped along the hills of light,\nYe Christian soldiers, rise,\nAnd press the battle ere the night\nShall veil the glowing skies.\nAgainst the foe in vales below,\nLet all our strength be hurled;\nFaith is the victory, we know,\nThat overcomes the world.\n\nRefrain:\nFaith is is the victory!\nFaith is is the victory!\nOh, glorious victory,\nThat overcomes the world.\n\nHis banner over us is love,\nOur sword the Word of God;\nWe tread the road the saints above\nWith shouts of triumph trod.\nBy faith they, like a whirlwind’s breath,\nSwept on o’er ev’ry field;\nThe faith by which they conquered death\nIs still our shining shield.\n\nOn ev’ry hand the foe we find\nDrawn up in dread array;\nLet tents of ease be left behind,\nAnd onward to the fray;\nSalvation’s helmet on each head,\nWith truth all girt about,\nThe earth shall tremble ’neath our tread,\nAnd echo with our shout.\n\nTo him that overcomes the foe,\nWhite raiment shall be giv’n;\nBefore the angels he shall know\nHis name confessed in heav’n.\nThen onward from the hills of light,\nOur hearts with love aflame,\nWe’ll vanquish all the hosts of night,\nIn Jesus’ conqu’ring name.\n\n',
  'FAITH OF OUR FATHERS':
      'Faith of our fathers, living still,\nIn spite of dungeon, fire and sword;\nO how our hearts beat high with joy\nWhenever we hear that glorious Word!\n\nRefrain\n\nFaith of our fathers, holy faith!\nWe will be true to thee till death.\n\nFaith of our fathers, we will strive\nTo win all nations unto Thee;\nAnd through the truth that comes from God,\nWe all shall then be truly free.\n\nRefrain\n\nFaith of our fathers, we will love\nBoth friend and foe in all our strife;\nAnd preach Thee, too, as love knows how\nBy kindly words and virtuous life.\n\nRefrain\n\n \n',
  'FIGHT THE GOOD FIGHT':
      'Fight the good fight with all thy might!\nChrist is thy strength, and Christ thy right;\nLay hold on life, and it shall be\nThy joy and crown eternally.\n\nRun the straight race thro’ God’s good grace,\nLift up thine eyes, and seek His face;\nLife with its way before us lies,\nChrist is the path, and Christ the prize.\n\nCast care aside, lean on thy Guide,\nHis boundless mercy will provide;\nTrust, and thy trusting soul shall prove\nChrist is its life, and Christ its love.\n\nFaint not nor fear, His arms are near,\nHe changeth not, and thou art dear;\nOnly believe, and thou shalt see\nThat Christ is all in all to thee.\n\n',
  'GOD LEADS HIS DEAR CHILDREN ALONG':
      'In shady, green pastures, so rich and so sweet,\nGod leads His dear children along;\nWhere the water’s cool flow bathes the weary one’s feet,\nGod leads His dear children along.\nRefrain\n\nSome through the waters, some through the flood,\nSome through the fire, but all through the blood;\nSome through great sorrow, but God gives a song,\nIn the night season and all the day long.\n\nSometimes on the mount where the sun shines so bright,\nGod leads His dear children along;\nSometimes in the valley, in darkest of night,\nGod leads His dear children along.\n\nRefrain\n\nThough sorrows befall us and evils oppose,\nGod leads His dear children along;\nThrough grace we can conquer, defeat all our foes,\nGod leads His dear children along.\n\nRefrain\n\nAway from the mire, and away from the clay,\nGod leads His dear children along;\nAway up in glory, eternity’s day,\nGod leads His dear children along.\n\nRefrain\n\n \n',
  'GOD WILL TAKE CARE OF YOU':
      'Be not dismayed whate’er betide,\nGod will take care of you;\nBeneath His wings of love abide,\nGod will take care of you.\n\nRefrain:\nGod will take care of you,\nThro’ ev’ry day, O’er all the way;\nHe will take care of you,\nGod will take care of you.\n\nThro’ days of toil when heart doth fail,\nGod will take care of you;\nWhen dangers fierce your path assail,\nGod will take care of you.\n\nAll you may need He will provide,\nGod will take care of you;\nTrust Him, and you will be satisfied,\nGod will take care of you.\n\nLonely or sad, from friends apart,\nGod will take care of you;\nHe will give peace to your aching heart,\nGod will take care of you.\n\nNo matter what may be the test,\nGod will take care of you;\nLean, weary one, upon His breast,\nGod will take care of you.\n\n',
  'GREAT IS THY FAITHFULNESS':
      'Great is Thy faithfulness, O God my Father;\nThere is no shadow of turning with Thee;\nThou changest not, Thy compassions, they fail not;\nAs Thou hast been, Thou forever will be.\n\nGreat is Thy faithfulness!\nGreat is Thy faithfulness!\nMorning by morning new mercies I see.\nAll I have needed Thy hand hath provided;\nGreat is Thy faithfulness, Lord, unto me!\n\nSummer and winter and springtime and harvest,\nSun, moon and stars in their courses above\nJoin with all nature in manifold witness\nTo Thy great faithfulness, mercy and love.\n\nGreat is Thy faithfulness!\nGreat is Thy faithfulness!\nMorning by morning new mercies I see.\nAll I have needed Thy hand hath provided;\nGreat is Thy faithfulness, Lord, unto me!\n\nPardon for sin and a peace that endureth\nThine own dear presence to cheer and to guide;\nStrength for today and bright hope for tomorrow,\nBlessings all mine, with ten thousand beside!\n\nGreat is Thy faithfulness!\nGreat is Thy faithfulness!\nMorning by morning new mercies I see.\nAll I have needed Thy hand hath provided;\nGreat is Thy faithfulness, Lord, unto me!\n \n',
  'HARK! THE HERALD ANGELS SING':
      'Hark! The herald angels sing,\n“Glory to the newborn King;\nPeace on earth, and mercy mild,\nGod and sinners reconciled!”\nJoyful, all ye nations rise,\nJoin the triumph of the skies;\nWith th’angelic host proclaim,\n“Christ is born in Bethlehem!”\n \nRefrain\n\nHark! the herald angels sing,\n“Glory to the newborn King!”\n\nChrist, by highest Heav’n adored;\nChrist the everlasting Lord;\nLate in time, behold Him come,\nOffspring of a virgin’s womb.\nVeiled in flesh the Godhead see;\nHail th’incarnate Deity,\nPleased with us in flesh to dwell,\nJesus our Emmanuel.\n\nRefrain\n\nHail the heav’nly Prince of Peace!\nHail the Sun of Righteousness!\nLight and life to all He brings,\nRis’n with healing in His wings.\nMild He lays His glory by,\nBorn that man no more may die.\nBorn to raise the sons of earth,\nBorn to give them second birth.\n\nRefrain\n\nCome, Desire of nations, come,\nFix in us Thy humble home;\nRise, the woman’s conqu’ring Seed,\nBruise in us the serpent’s head.\nNow display Thy saving power,\nRuined nature now restore;\nNow in mystic union join\nThine to ours, and ours to Thine.\n\nRefrain\n\nAdam’s likeness, Lord, efface,\nStamp Thine image in its place:\nSecond Adam from above,\nReinstate us in Thy love.\nLet us Thee, though lost, regain,\nThee, the Life, the inner man:\nO, to all Thyself impart,\nFormed in each believing heart.\n\nRefrain\n\n \n \n',
  'HAVE THINE OWN WAY LORD':
      'Have Thine own way, Lord, Have Thine own way;\nThou art the Potter; I am the clay.\nMould me and make me After Thy will,\nWhile I am waiting, Yielded and still.\n\nHave Thine own way, Lord, Have Thine own way;\nSearch me and try me, Master, today.\nWhiter than snow, Lord, Wash me just now,\nAs in Thy presence Humbly I bow.\n\nHave Thine own way, Lord, Have Thine own way;\nWounded and weary, Help me, I pray.\nPower, all power, Surely is Thine;\nTouch me and heal me, Saviour divine.\n\nHave Thine own way, Lord, Have Thine own way;\nHold o’er my being Absolute sway.\nFill with Thy Spirit Till all shall see\nChrist only, always, Living in me.\n\n',
  'HE HIDETH MY SOUL':
      'A wonderful Savior is Jesus my Lord,\nA wonderful Savior to me;\nHe hideth my soul in the cleft of the rock,\nWhere rivers of pleasure I see.\nRefrain\n\nHe hideth my soul in the cleft of the rock\nThat shadows a dry, thirsty land;\nHe hideth my life with the depths of His love,\nAnd covers me there with His hand,\nAnd covers me there with His hand.\n\nA wonderful Savior is Jesus my Lord,\nHe taketh my burden away;\nHe holdeth me up, and I shall not be moved,\nHe giveth me strength as my day.\n\nRefrain\n\nWith numberless blessings each moment He crowns,\nAnd filled with His fullness divine,\nI sing in my rapture, oh, glory to God\nFor such a Redeemer as mine!\n\nRefrain\n\nWhen clothed in His brightness, transported I rise\nTo meet Him in clouds of the sky,\nHis perfect salvation, His wonderful love\nI’ll shout with the millions on high.\n\nRefrain\n\n \n \n',
  'HE IS COMING AGAIN':
      'Lift up your heads, pilgrims aweary,\nSee day’s approach now crimson the sky;\nNight shadows flee, and your Belovèd,\nAwaited with longing, at last draweth nigh.\n\nRefrain\n\nHe is coming again, He is coming again,\nThe very same Jesus, rejected of men;\nHe is coming again, He is coming again,\nWith power and great glory, He is coming again!\n\nDark was the night, sin warred against us;\nHeavy the load of sorrow we bore;\nBut now we see signs of His coming;\nOur hearts glow within us, joy’s cup runneth o’er!\n\nRefrain\n\nO blessèd hope! O blissful promise!\nFilling our hearts with rapture divine;\nO day of days! Hail Thy appearing!\nThy transcendent glory forever shall shine.\n\nRefrain\n\nEven so, come, precious Lord Jesus;\nCreation waits redemption to see;\nCaught up in clouds, soon we shall meet Thee;\nO blessèd assurance, forever with Thee!\nRefrain\n \n',
  'HE LIVES':
      'I serve a risen Savior, He’s in the world today;\nI know that He is living whatever men may say;\nI see His hand of mercy, I hear His voice of cheer,\nAnd just the time I need Him, He’s always near.\n\nChorus\nHe lives, He lives,\nChrist Jesus lives today!\nHe walks with me and talks with me\nAlong life’s narrow way.\nHe lives, He lives,\nSalvation to impart!\nYou ask me how I know He lives?\nHe lives within my heart.\nIn all the world around me I see His loving care,\nAnd tho’ my heart grows weary I never will despair;\nI know that He is leading thro’ all the stormy blast,\nThe day of His appearing will come at last.\n\nChorus\nHe lives, He lives,\nChrist Jesus lives today!\nHe walks with me and talks with me\nAlong life’s narrow way.\nHe lives, He lives,\nSalvation to impart!\nYou ask me how I know He lives?\nHe lives within my heart.\nRejoice, rejoice, O Christian, lift up your voice and sing\nEternal hallelujahs to Jesus Christ the King!\nThe hope of all who seek Him, the help of all who find,\nNone other is so loving, so good and kind.\n\nChorus\nHe lives, He lives,\nChrist Jesus lives today!\nHe walks with me and talks with me\nAlong life’s narrow way.\nHe lives, He lives,\nSalvation to impart!\nYou ask me how I know He lives?\nHe lives within my heart.\n \n \n \n',
  'HIS EYE IS ON THE SPARROW':
      'Why should I feel discouraged, why should the shadows come,\nWhy should my heart be lonely, and long for heaven and home,\nWhen Jesus is my portion? My constant friend is He:\nHis eye is on the sparrow, and I know He watches me;\nHis eye is on the sparrow, and I know He watches me.\n\nRefrain\n\nI sing because I’m happy,\nI sing because I’m free,\nFor His eye is on the sparrow,\nAnd I know He watches me.\n\n“Let not your heart be troubled,” His tender word I hear,\nAnd resting on His goodness, I lose my doubts and fears;\nThough by the path He leadeth, but one step I may see;\nHis eye is on the sparrow, and I know He watches me;\nHis eye is on the sparrow, and I know He watches me.\n\nRefrain\n\nWhenever I am tempted, whenever clouds arise,\nWhen songs give place to sighing, when hope within me dies,\nI draw the closer to Him, from care He sets me free;\nHis eye is on the sparrow, and I know He watches me;\nHis eye is on the sparrow, and I know He watches me.\n\nRefrain\n\n',
  'HOLY, HOLY, HOLY':
      'Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy, merciful and mighty!\nGod in three Persons, blessèd Trinity!\n\nHoly, holy, holy! All the saints adore Thee,\nCasting down their golden crowns around the glassy sea;\nCherubim and seraphim falling down before Thee,\nWho was, and is, and evermore shall be.\n\nHoly, holy, holy! though the darkness hide Thee,\nThough the eye of sinful man Thy glory may not see;\nOnly Thou art holy; there is none beside Thee,\nPerfect in power, in love, and purity.\n\nHoly, holy, holy! Lord God Almighty!\nAll Thy works shall praise Thy Name, in earth, and sky, and sea;\nHoly, holy, holy; merciful and mighty!\nGod in three Persons, blessèd Trinity!\n\n \n',
  'HOW GREAT THOU ART':
      'O Lord my God! When I in awesome wonder\nConsider all the worlds Thy hands have made,\nI see the stars, I hear the rolling thunder,\nThy power throughout the universe displayed,\n\nRefrain:\nThen sings my soul, my Saviour God to Thee;\nHow great Thou art, how great Thou art!\nThen sings my soul, my Saviour God to Thee;\nHow great Thou art, how great Thou art!\n\nWhen through the woods and forest glades I wander\nAnd hear the birds sing sweetly in the trees;\nWhen I look down from lofty mountain grandeur\nAnd hear the brook and feel the gentle breeze;\n\nAnd when I think that God, His Son not sparing\nSent Him to die, I scarce can take it in;\nThat on the cross, my burden gladly bearing,\nHe bled and died to take away my sin;\n\nWhen Christ shall come with shout of acclamation\nAnd take me home, what joy shall fill my heart!\nThen I shall bow in humble adoration\nAnd there proclaim, my God, how great Thou art!\n\n',
  'I AM THINE, O LORD':
      'I am Thine, O Lord, I have heard Thy voice,\nAnd it told Thy love to me;\nBut I long to rise in the arms of faith\nAnd be closer drawn to Thee.\n\nRefrain\n\nDraw me nearer, nearer blessèd Lord,\nTo the cross where Thou hast died.\nDraw me nearer, nearer, nearer blessèd Lord,\nTo Thy precious, bleeding side.\n\nConsecrate me now to Thy service, Lord,\nBy the power of grace divine;\nLet my soul look up with a steadfast hope,\nAnd my will be lost in Thine.\n\nRefrain\n\nO the pure delight of a single hour\nThat before Thy throne I spend,\nWhen I kneel in prayer, and with Thee, my God\nI commune as friend with friend!\n\nRefrain\n\nThere are depths of love that I cannot know\nTill I cross the narrow sea;\nThere are heights of joy that I may not reach\nTill I rest in peace with Thee.\n\nRefrain\n\n',
  'I LOVE TO TELL THE STORY':
      'I love to tell the story of unseen things above,\nOf Jesus and His glory, of Jesus and His love.\nI love to tell the story, because I know ’tis true;\nIt satisfies my longings as nothing else can do.\nRefrain\n\nI love to tell the story, ’twill be my theme in glory,\nTo tell the old, old story of Jesus and His love.\n\nI love to tell the story; more wonderful it seems\nThan all the golden fancies of all our golden dreams.\nI love to tell the story, it did so much for me;\nAnd that is just the reason I tell it now to thee.\n\nRefrain\n\nI love to tell the story; ’tis pleasant to repeat\nWhat seems, each time I tell it, more wonderfully sweet.\nI love to tell the story, for some have never heard\nThe message of salvation from God’s own holy Word.\n\nRefrain\n\nI love to tell the story, for those who know it best\nSeem hungering and thirsting to hear it like the rest.\nAnd when, in scenes of glory, I sing the new, new song,\n’Twill be the old, old story that I have loved so long.\n\nRefrain\n\n \n \n',
  'I NEED THEE EV’RY HOUR':
      'I need Thee ev’ry hour,\nMost gracious Lord;\nNo tender voice like Thine\nCan peace afford.\n\nRefrain:\nI need Thee, O I need Thee!\nEv’ry hour I need Thee;\nO bless me now, my Saviour!\nI come to Thee.\n\nI need Thee ev’ry hour;\nStay Thou nearby;\nTemptations lose their pow’r\nWhen Thou art nigh.\n\nI need Thee ev’ry hour,\nIn joy or pain;\nCome quickly and abide,\nOr life is vain.\n\nI need Thee ev’ry hour;\nTeach me Thy will,\nAnd Thy rich promises\nIn me fulfill.\n\nI need Thee ev’ry hour,\nMost Holy One;\nO make me Thine indeed,\nThou blessed Son!\n\n',
  'I SURRENDER ALL':
      'All to Jesus, I surrender;\nAll to Him I freely give;\nI will ever love and trust Him,\nIn His presence daily live.\n\nRefrain\n\nI surrender all, I surrender all,\nAll to Thee, my blessèd Savior,\nI surrender all.\n\nAll to Jesus I surrender;\nHumbly at His feet I bow,\nWorldly pleasures all forsaken;\nTake me, Jesus, take me now.\n\nRefrain\n\nAll to Jesus, I surrender;\nMake me, Savior, wholly Thine;\nLet me feel the Holy Spirit,\nTruly know that Thou art mine.\n\nRefrain\n\nAll to Jesus, I surrender;\nLord, I give myself to Thee;\nFill me with Thy love and power;\nLet Thy blessing fall on me.\n\nRefrain\n\nAll to Jesus I surrender;\nNow I feel the sacred flame.\nO the joy of full salvation!\nGlory, glory, to His Name!\n\nRefrain\n\n \n',
  'I’D RATHER HAVE JESUS':
      'I’d rather have Jesus than silver or gold;\nI’d rather be His than have riches untold;\nI’d rather have Jesus than houses or lands;\nI’d rather be led by His nail-pierced hand\n\nRefrain:\nThan to be the king of a vast domain,\nOr be held in sin’s dread sway;\nI’d rather have Jesus than anything\nThis world affords today.\n\nI’d rather have Jesus than men’s applause;\nI’d rather be faithful to His dear cause;\nI’d rather have Jesus than worldwide fame;\nI’d rather be true to His holy name\n\nHe’s fairer than lilies of rarest bloom;\nHe’s sweeter than honey from out the comb;\nHe’s all that my hungering spirit needs;\nI’d rather have Jesus and let Him lead\n \n \n',
  'I’LL FLY AWAY':
      '1.\nSome glad morning when this life is o’er,\nI’ll fly away;\nTo a home on God’s celestial shore,\nI’ll fly away (I’ll fly away).\n\nChorus\nI’ll fly away, Oh Glory\nI’ll fly away; (in the morning)\nWhen I die, Hallelujah, by and by,\nI’ll fly away (I’ll fly away).\n\n2.\nWhen the shadows of this life have gone,\nI’ll fly away;\nLike a bird from prison bars has flown,\nI’ll fly away (I’ll fly away)\n\nChorus\n\n3.\nJust a few more weary days and then,\nI’ll fly away;\nTo a land where joy shall never end,\nI’ll fly away (I’ll fly away) \n\n',
  'IN THE GARDEN':
      'I come to the garden alone\nWhile the dew is still on the roses\nAnd the voice I hear falling on my ear\nThe Son of God discloses.\n\nRefrain\n\nAnd He walks with me, and He talks with me,\nAnd He tells me I am His own;\nAnd the joy we share as we tarry there,\nNone other has ever known.\n\nHe speaks, and the sound of His voice,\nIs so sweet the birds hush their singing,\nAnd the melody that He gave to me\nWithin my heart is ringing.\n\nRefrain\n\nI’d stay in the garden with Him\nThough the night around me be falling,\nBut He bids me go; through the voice of woe\nHis voice to me is calling.\n\nRefrain\n\n \n',
  'IN THE HOUR OF TRIAL':
      'In the hour of trial, Jesus, plead for me,\nLest by base denial I depart from Thee.\nWhen Thou seest me waver, with a look recall,\nNor for fear or favor suffer me to fall.\nWith forbidden pleasures would this vain world charm,\nOr its sordid treasures spread to work me harm,\nBring to my remembrance sad Gethsemane,\nOr, in darker semblance, cross-crowned Calvary.\n\nShould Thy mercy send me sorrow, toil and woe,\nOr should pain attend me on my path below,\nGrant that I may never fail Thy hand to see;\nGrant that I may ever cast my care on Thee.\n\nWhen my last hour cometh, fraught with strife and pain,\nWhen my dust returneth to the dust again,\nOn Thy truth relying, through that mortal strife,\nJesus, take me, dying, to eternal life.\n\n \n',
  'IN THE SWEET BY AND BY':
      'There’s a land that is fairer than day,\nAnd by faith we can see it afar;\nFor the Father waits over the way,\nTo prepare us a dwelling-place there.\n\nRefrain:\nIn the sweet by and by\nWe shall meet on that beautiful shore;\nIn the sweet by and by\nWe shall meet on that beautiful shore.\n\nWe shall sing on that beautiful shore\nThe melodious songs of the blessed;\nAnd our spirits shall sorrow no more,\nNot a sigh for the blessing of rest.\n\nTo our bountiful Father above,\nWe will offer our tribute of praise,\nFor the glorious gift of His love,\nAnd the blessings that hallow our days.\n\n',
  'IT IS WELL':
      'When peace, like a river, attendeth my way,\nWhen sorrows like sea billows roll;\nWhatever my lot, Thou has taught me to say,\nIt is well, it is well, with my soul.\n\nRefrain:\nIt is well, with my soul,\nIt is well, with my soul,\nIt is well, it is well, with my soul.\n\nThough Satan should buffet, though trials should come,\nLet this blest assurance control,\nThat Christ has regarded my helpless estate,\nAnd hath shed His own blood for my soul.\n\nRefrain\n\nMy sin, oh, the bliss of this glorious thought!\nMy sin, not in part but the whole,\nIs nailed to the cross, and I bear it no more,\nPraise the Lord, praise the Lord, O my soul!\n\nRefrain\n\nFor me, be it Christ, be it Christ hence to live:\nIf Jordan above me shall roll,\nNo pang shall be mine, for in death as in life\nThou wilt whisper Thy peace to my soul.\n\nRefrain\n\nBut, Lord, ‘tis for Thee, for Thy coming we wait,\nThe sky, not the grave, is our goal;\nOh trump of the angel! Oh voice of the Lord!\nBlessèd hope, blessèd rest of my soul!\n\nRefrain\n\nAnd Lord, haste the day when my faith shall be sight,\nThe clouds be rolled back as a scroll;\nThe trump shall resound, and the Lord shall descend,\nEven so, it is well with my soul.\n\nRefrain\n\n',
  'JESUS, LOVER OF MY SOUL':
      'Jesus, Lover of my soul,\nLet me to Thy bosom fly,\nWhile the nearer waters roll,\nWhile the tempest still is high:\nHide me, O my Saviour, hide,\nTill the storm of life is past;\nSafe into the haven guide;\nO receive my soul at last!\n\nOther refuge have I none;\nHangs my helpless soul on Thee;\nLeave, ah! leave me not alone,\nStill support and comfort me.\nAll my trust on Thee is stayed,\nAll my help from Thee I bring;\nCover my defenseless head\nWith the shadow of Thy wing.\n\nWilt Thou not regard my call?\nWilt Thou not accept my prayer?\nLo! I sink, I faint, I fall!\nLo, on Thee I cast my care!\nReach me out Thy gracious hand!\nWhile I of Thy strength receive;\nHoping against hope I stand,\nDying, and behold I live.\n\nThou, O Christ, art all I want;\nMore than all in Thee I find;\nRaise the fallen, cheer the faint,\nHeal the sick, and lead the blind.\nJust and holy is Thy name,\nI am all unrighteousness;\nVile and full of sin I am,\nThou art full of truth and grace.\n\nPlenteous grace with Thee is found,\nGrace to cover all my sin;\nLet the healing streams abound;\nMake and keep me pure within.\nThou of life the Fountain art,\nFreely let me take of Thee;\nSpring Thou up within my heart,\nRise to all eternity.\n\n',
  'JESUS LOVES ME':
      'Jesus loves me! this I know,\nFor the Bible tells me so;\nLittle ones to Him belong,\nThey are weak, but He is strong.\n\nRefrain:\nYes, Jesus loves me,\nYes, Jesus loves me,\nYes, Jesus loves me,\nThe Bible tells me so.\n\nJesus loves me! He who died,\nHeaven’s gate to open wide;\nHe will wash away my sin,\nThat His child may enter in.\n\nJesus loves me! loves me still,\nWhen I’m very weak and ill;\nFrom His shining throne on high,\nWatches o’er me where I lie.\n\nJesus loves me! He will stay\nClose beside me all the way;\nIf I trust Him, when I die\nHe will take me home on high.\n\n',
  'JESUS PAID IT ALL':
      'I hear the Savior say,\n“Thy strength indeed is small;\nChild of weakness, watch and pray,\nFind in Me thine all in all.”\nRefrain\n\nJesus paid it all,\nAll to Him I owe;\nSin had left a crimson stain,\nHe washed it white as snow.\n\nFor nothing good have I\nWhereby Thy grace to claim,\nI’ll wash my garments white\nIn the blood of Calv’ry’s Lamb.\n\nRefrain\n\nAnd now complete in Him\nMy robe His righteousness,\nClose sheltered ’neath His side,\nI am divinely blest.\n\nRefrain\n\nLord, now indeed I find\nThy power and Thine alone,\nCan change the leper’s spots\nAnd melt the heart of stone.\n\nRefrain\n\nWhen from my dying bed\nMy ransomed soul shall rise,\n“Jesus died my soul to save,”\nShall rend the vaulted skies.\n\nRefrain\n\nAnd when before the throne\nI stand in Him complete,\nI’ll lay my trophies down\nAll down at Jesus’ feet.\n\nRefrain\n\n \n \n \n',
  'JUST AS I AM':
      'Just as I am, without one plea\nBut that Thy blood was shed for me,\nAnd that Thou bidd’st me come to Thee,\nO Lamb of God, I come, I come.\n\nJust as I am, and waiting not\nTo rid my soul of one dark blot,\nTo Thee, whose blood can cleanse each spot,\nO Lamb of God, I come, I come.\n\nJust as I am, tho’ tossed about\nWith many many a conflict, many a doubt,\nFightings and fears within, without,\nO Lamb of God, I come, I come.\n\nJust as I am, poor, wretched, blind:\nSight, riches, healing of the mind,\nYea, all I need in Thee to find,\nO Lamb of God, I come, I come.\n\nJust as I am, Thou wilt receive,\nWilt welcome, pardon, cleanse, relieve;\nBecause Thy promise I believe,\nO Lamb of God, I come, I come.\n\nJust as I am— Thy love unknown\nHath broken ev’ry barrier down;\nNow to be Thine, yea, Thine alone,\nO Lamb of God, I come, I come. \n\n',
  'LEANING ON THE EVERLASTING ARMS':
      'What a fellowship, what a joy divine,\nLeaning on the everlasting arms!\nWhat a blessedness, what a peace is mine,\nLeaning on the everlasting arms!\n\nRefrain:\nLeaning, leaning,\nSafe and secure from all alarms;\nLeaning, leaning,\nLeaning on the everlasting arms.\n\nO how sweet to walk in this pilgrim way,\nLeaning on the everlasting arms!\nO how bright the path grows from day to day,\nLeaning on the everlasting arms!\n\nWhat have I to dread, what have I to fear,\nLeaning on the everlasting arms!\nI have blessed peace with my Lord so near,\nLeaning on the everlasting arms.\n\n',
  'LORD, I’M COMING HOME':
      'I’ve wandered far away from God:\nNow I’m coming home;\nThe paths of sin too long I’ve trod:\nLord, I’m coming home.\n\nRefrain:\nComing home, coming home,\nNevermore to roam;\nOpen wide Thine arms of love:\nLord, I’m coming home.\n\nI’ve wasted many precious years:\nNow I’m coming home;\nI now repent with bitter tears:\nLord, I’m coming home.\n\nI’m tired of sin and straying, Lord:\nNow I’m coming home;\nI’ll trust Thy love, believe Thy Word;\nLord, I’m coming home.\n\nMy soul is sick, my heart is sore:\nNow I’m coming home;\nMy strength renew, my hope restore:\nLord, I’m coming home.\n\nMy only hope, my only plea:\nNow I’m coming home;\nThat Jesus died, and died for me:\nLord, I’m coming home.\n\nI need His cleansing blood, I know:\nNow I’m coming home;\nO wash me whiter than the snow:\nLord, I’m coming home.\n\n',
  'LOVE LIFTED ME':
      'I was sinking deep in sin, far from the peaceful shore,\nVery deeply stained within, sinking to rise no more,\nBut the Master of the sea, heard my despairing cry,\nFrom the waters lifted me, now safe am I.\n\nRefrain\n\nLove lifted me! Love lifted me!\nWhen nothing else could help\nLove lifted me!\n\nAll my heart to Him I give, ever to Him I’ll cling\nIn His blessèd presence live, ever His praises sing,\nLove so mighty and so true, merits my soul’s best songs,\nFaithful, loving service too, to Him belongs.\n\nRefrain\n\nSouls in danger look above, Jesus completely saves,\nHe will lift you by His love, out of the angry waves.\nHe’s the Master of the sea, billows His will obey,\nHe your Savior wants to be, be saved today.\n\nRefrain\n\n\n',
  'MOMENT BY MOMENT':
      'Dying with Jesus, by death reckoned mine;\nLiving with Jesus, a new life divine;\nLooking to Jesus till glory doth shine,\nMoment by moment, O Lord, I am Thine.\nRefrain\n\nMoment by moment I’m kept in His love;\nMoment by moment I’ve life from above;\nLooking to Jesus till glory doth shine;\nMoment by moment, O Lord, I am Thine.\n\nNever a trial that He is not there,\nNever a burden that He doth not bear,\nNever a sorrow that He doth not share,\nMoment by moment, I’m under His care.\n\nRefrain\n\nNever a heartache, and never a groan,\nNever a teardrop and never a moan;\nNever a danger but there on the throne,\nMoment by moment He thinks of His own.\n\nRefrain\n\nNever a weakness that He doth not feel,\nNever a sickness that He cannot heal;\nMoment by moment, in woe or in weal,\nJesus my Savior, abides with me still.\n\nRefrain\n\n\n',
  'MORE LOVE TO THEE':
      'More love to Thee, O Christ, more love to Thee!\nHear Thou the prayer I make on bended knee.\nThis is my earnest plea: More love, O Christ, to Thee;\nMore love to Thee, more love to Thee!\n\nOnce earthly joy I craved, sought peace and rest;\nNow Thee alone I seek, give what is best.\nThis all my prayer shall be: More love, O Christ to Thee;\nMore love to Thee, more love to Thee!\n\nLet sorrow do its work, come grief or pain;\nSweet are Thy messengers, sweet their refrain,\nWhen they can sing with me: More love, O Christ, to Thee;\nMore love to Thee, more love to Thee!\n\nThen shall my latest breath whisper Thy praise;\nThis be the parting cry my heart shall raise;\nThis still its prayer shall be: More love, O Christ to Thee;\nMore love to Thee, more love to Thee!\n\n \n',
  'MORNING HAS BROKEN':
      'Morning has broken, like the first morning\nBlackbird has spoken, like the first bird\nPraise for the singing, Praise for the morning\nPraise for them springing fresh from the word\n\nSweet the rain’s new fall, sunlit from heaven\nLike the first dew fall, on the first grass\nPraise for the sweetness of the wet garden\nSprung in completeness, where his feet pass\n\nMine is the sunlight, mine is the morning\nBorn of the one light, Eden saw play\nPraise with elation, praise every morning\nGod’s recreation of the new day\n\n',
  'MY FAITH LOOKS UP TO THEE':
      'My faith looks up to Thee,\nThou Lamb of Calvary,\nSaviour divine!\nNow hear me while I pray;\nTake all my guilt away;\nO let me from this day\nBe wholly Thine!\n\nMay Thy rich grace impart\nStrength to my fainting heart,\nMy zeal inspire;\nAs Thou hast died for me,\nO may my love to Thee\nPure, warm, and changeless be,\nA living fire.\n\nWhile life’s dark maze I tread,\nAnd griefs around me spread,\nBe Thou my guide;\nBid darkness turn to day,\nWipe sorrow’s tears away,\nNor let me ever stray\nFrom Thee aside.\n\nWhen ends life’s transient dream,\nWhen death’s cold, sullen stream\nShall o’er me roll;\nBlest Saviour, then, in love,\nFear and distrust remove;\nO bear me safe above,\nA ransomed soul.\n\n',
  'NEARER MY GOD, TO THEE':
      'Nearer, my God, to Thee, nearer to Thee!\nE’en though it be a cross that raiseth me,\nStill all my song shall be, nearer, my God, to Thee.\n\nRefrain:\n\nNearer, my God, to Thee,\nNearer to Thee!\n\nThough like the wanderer, the sun gone down,\nDarkness be over me, my rest a stone.\nYet in my dreams I’d be nearer, my God to Thee.\n\nRefrain\n\nThere let the way appear, steps unto Heav’n;\nAll that Thou sendest me, in mercy given;\nAngels to beckon me nearer, my God, to Thee.\n\nRefrain\n\nThen, with my waking thoughts bright with Thy praise,\nOut of my stony griefs Bethel I’ll raise;\nSo by my woes to be nearer, my God, to Thee.\n\nRefrain\n\nOr, if on joyful wing cleaving the sky,\nSun, moon, and stars forgot, upward I’ll fly,\nStill all my song shall be, nearer, my God, to Thee.\n\nRefrain\n\nThere in my Father’s home, safe and at rest,\nThere in my Savior’s love, perfectly blest;\nAge after age to be, nearer my God to Thee.\n\nRefrain\n\n',
  'NOW THANK WE ALL OUR GOD':
      'Now thank we all our God\nWith hearts and hands and voices,\nWho wondrous things hath done,\nIn Whom His world rejoices;\nWho, from our mothers’ arms,\nHath blessed us on our way\nWith countless gifts of love,\nAnd still is ours today.\n\nO may this bounteous God\nThrough all our life be near us,\nWith ever joyful hearts\nAnd blessed peace to cheer us,\nAnd keep us in His grace,\nAnd guide us when perplexed,\nAnd free us from all ills\nIn this world and the next.\n\nAll praise and thanks to God\nThe Father now be given,\nThe Son, and Him Who reigns\nWith them in highest heaven,\nThe one eternal God,\nWhom earth and heav’n adore;\nFor thus it was, is now,\nAnd shall be evermore.\n\n',
  'O COME ALL YE FAITHFUL':
      'O come, all ye faithful, joyful and triumphant,\nO come ye, O come ye, to Bethlehem.\nCome and behold Him, born the King of angels;\n\nRefrain\n\nO come, let us adore Him,\nO come, let us adore Him,\nO come, let us adore Him,\nChrist the Lord.\nTrue God of true God, Light from Light Eternal,\nLo, He shuns not the Virgin’s womb;\nSon of the Father, begotten, not created;\n\nRefrain\n\nSing, choirs of angels, sing in exultation;\nO sing, all ye citizens of heaven above!\nGlory to God, all glory in the highest;\n\nRefrain\n\nSee how the shepherds, summoned to His cradle,\nLeaving their flocks, draw nigh to gaze;\nWe too will thither bend our joyful footsteps;\n\nRefrain\n\nLo! star led chieftains, Magi, Christ adoring,\nOffer Him incense, gold, and myrrh;\nWe to the Christ Child bring our hearts’ oblations.\n\nRefrain\n\nChild, for us sinners poor and in the manger,\nWe would embrace Thee, with love and awe;\nWho would not love Thee, loving us so dearly?\n\nRefrain\n\nYea, Lord, we greet Thee, born this happy morning;\nJesus, to Thee be glory given;\nWord of the Father, now in flesh appearing.\n\nRefrain\n\n',
  'O FOR A THOUSAND TONGUES TO SING':
      'O for a thousand tongues to sing\nMy great Redeemer’s praise,\nMy great Redeemer’s praise,\nThe glories of my God and King,\nThe triumphs of His grace,\nThe triumphs of His grace,\nThe triumphs of His grace.\n\nMy gracious Master and my God,\nAssist me to proclaim,\nAssist me to proclaim,\nTo spread thro’ all the earth abroad\nThe honors of Thy name,\nThe honors of Thy name,\nThe honors of Thy name.\n\nJesus! the name that charms our fears,\nThat bids our sorrows cease,\nThat bids our sorrows cease;\n’Tis music in the sinner’s ears,\n’Tis life, and health, and peace,\n’Tis life, and health, and peace,\n’Tis life, and health, and peace.\n\nHe breaks the pow’r of canceled sin,\nHe sets the pris’ner free,\nHe sets the pris’ner free.\nHis blood can make the foulest clean,\nHis blood availed for me,\nHis blood availed for me,\nHis blood availed for me.\n\n \n',
  'O HOLY NIGHT':
      'O holy night, the stars are brightly shining;\nIt is the night of the dear Savior’s birth!\nLong lay the world in sin and error pining,\nTill He appeared and the soul felt its worth.\nA thrill of hope, the weary soul rejoices,\nFor yonder breaks a new and glorious morn.\nFall on your knees, O hear the angel voices!\nO night divine, O night when Christ was born!\nO night, O holy night, O night divine!\nLed by the light of faith serenely beaming,\nWith glowing hearts by His cradle we stand.\nSo led by light of a star sweetly gleaming,\nHere came the wise men from Orient land.\nThe King of kings lay thus in lowly manger,\nIn all our trials born to be our Friend!\nHe knows our need—to our weakness is no stranger.\nBehold your King; before Him lowly bend!\nBehold your King; before Him lowly bend!\n\nTruly He taught us to love one another;\nHis law is love and His Gospel is peace.\nChains shall He break for the slave is our brother\nAnd in His Name all oppression shall cease.\nSweet hymns of joy in grateful chorus raise we,\nLet all within us praise His holy Name!\nChrist is the Lord! O praise His name forever!\nHis pow’r and glory evermore proclaim!\nHis pow’r and glory evermore proclaim!\n\n \n',
  'O LITTLE TOWN OF BETHLEHEM':
      'O little town of Bethlehem, How still we see thee lie!\nAbove thy deep and dreamless sleep The silent stars go by.\nYet in thy dark streets shineth The everlasting Light;\nThe hopes and fears of all the years Are met in thee tonight.\n\nFor Christ is born of Mary, And gathered all above,\nWhile mortals sleep, the angels keep Their watch of wond’ring love.\nO morning stars, together Proclaim the holy birth!\nAnd praises sing to God the King, And peace to men on earth.\n\nHow silently, how silently, The wondrous gift is giv’n!\nSo God imparts to human hearts The blessings of His heav’n.\nNo ear may hear His coming, But in this world of sin,\nWhere meek souls will receive Him still, The dear Christ enters in.\n\nO holy Child of Bethlehem! Descend to us, we pray;\nCast out our sin, and enter in; Be born in us today.\nWe hear the Christmas angels The great glad tidings tell;\nO come to us, abide with us, Our Lord Emmanuel.\n \n',
  'O WORSHIP THE KING':
      'O worship the King, all glorious above,\nO gratefully sing His pow’r and His love;\nOur Shield and Defender, the Ancient of Days,\nPavilioned in splendor, and girded with praise.\n\nO tell of His might, O sing of His grace,\nWhose robe is the light, whose canopy canopy space.\nHis chariots of wrath the deep thunderclouds form,\nAnd dark is His path on the wings of the storm.\n\nThe earth, with its store of wonders untold,\nAlmighty, Thy pow’r hath founded of old,\nHath stablished it fast by a changeless decree,\nAnd round it hath cast, like a mantle, the sea.\n\nThy bountiful care what tongue can recite?\nIt breathes in the air, it shines in the light,\nIt streams from the hills, it descends to the plain,\nAnd sweetly distills in the dew and the rain.\n\nFrail children of dust, and feeble as frail,\nIn Thee do we trust, nor find Thee to fail;\nThy mercies how tender! how firm to the end!\nOur Maker, Defender, Redeemer, and Friend.\nO measureless might! Ineffable love!\nWhile angels delight to worship Thee above,\nThe humbler creation, though feeble their lays,\nWith true adoration shall all sing Thy praise.\n \n \n',
  'OLD TIME RELIGION':
      'Refrain\n\n’Tis the old time religion,\n[or Give me that old time religion]\n’Tis the old time religion,\n’Tis the old time religion,\nAnd it’s good enough for me.\n\nIt was good for our mothers.\nIt was good for our mothers.\nIt was good for our mothers.\nAnd it’s good enough for me.\n\nRefrain\n\nMakes me love everybody.\nMakes me love everybody.\nMakes me love everybody.\nAnd it’s good enough for me.\n\nRefrain\n\nIt has saved our fathers.\nIt has saved our fathers.\nIt has saved our fathers.\nAnd it’s good enough for me.\n\nRefrain\n\nIt will do when I am dying.\nIt will do when I am dying.\nIt will do when I am dying.\nAnd it’s good enough for me.\n\nRefrain\n\nIt will take us all to heaven.\nIt will take us all to heaven.\nIt will take us all to heaven.\nAnd it’s good enough for me.\n\nRefrain\n\n',
  'PASS ME NOT, O GENTLE SAVIOR':
      'Pass me not, O gentle Savior,\nHear my humble cry;\nWhile on others Thou art calling,\nDo not pass me by.\nRefrain\n\nSavior, Savior,\nHear my humble cry;\nWhile on others Thou art calling,\nDo not pass me by.\n\nLet me at Thy throne of mercy\nFind a sweet relief,\nKneeling there in deep contrition;\nHelp my unbelief.\n\nRefrain\n\nTrusting only in Thy merit,\nWould I seek Thy face;\nHeal my wounded, broken spirit,\nSave me by Thy grace.\n\nRefrain\n\nThou the Spring of all my comfort,\nMore than life to me,\nWhom have I on earth beside Thee?\nWhom in Heav’n but Thee?\n\nRefrain\n\n \n',
  'PEACE, PERFECT PEACE':
      'Peace, perfect peace, in this dark world of sin?\nThe blood of Jesus whispers peace within.\nPeace, perfect peace, by thronging duties pressed?\nTo do the will of Jesus, this is rest.\n\nPeace, perfect peace, with sorrows surging round?\nOn Jesus’ bosom naught but calm is found.\n\nPeace, perfect peace, with loved ones far away?\nIn Jesus’ keeping we are safe, and they.\n\nPeace, perfect peace, our future all unknown?\nJesus we know, and He is on the throne.\n\nPeace, perfect peace, death shadowing us and ours?\nJesus has vanquished death and all its powers.\n\nIt is enough: earth’s struggles soon shall cease,\nAnd Jesus call us to Heaven’s perfect peace.\n\n \n',
  'PRAISE HIM! PRAISE HIM!':
      'Praise Him! praise Him! Jesus, our blessed Redeemer!\nSing, O earth, His wonderful love proclaim!\nHail Him! hail Him! highest archangels in glory;\nStrength and honor give to His holy name!\nLike a shepherd Jesus will guard His children,\nIn His arms He carries them all day long:\n\nRefrain:\nPraise Him! praise Him! tell of His excellent greatness;\nPraise Him! praise Him! ever in joyful song!\n\nPraise Him! praise Him! Jesus, our blessed Redeemer!\nFor our sins He suffered, and bled and died;\nHe, our Rock, our hope of eternal salvation,\nHail Him! hail Him! Jesus the Crucified!\nSound His praises! Jesus who bore our sorrows;\nLove unbounded, wonderful, deep and strong;\n\nRefrain:\nPraise Him! praise Him! tell of His excellent greatness;\nPraise Him! praise Him! ever in joyful song!\n\nPraise Him! praise Him! Jesus, our blessed Redeemer!\nHeav’nly portals loud with hosannas ring!\nJesus, Saviour, reigneth forever and ever;\nCrown Him! crown Him! Prophet and Priest and King!\nChrist is coming! over the world victorious,\nPow’r and glory unto the Lord belong:\n\nRefrain:\nPraise Him! praise Him! tell of His excellent greatness;\nPraise Him! praise Him! ever in joyful song!\n\n',
  'PRECIOUS LORD TAKE MY HAND':
      'Precious Lord, take my hand,\nLead me on, let me stand,\nI am tired, I am weak, I am worn;\nThrough the storm, through the night,\nLead me on to the light:\n\nRefrain\n\nTake my hand, precious Lord,\nLead me home.\n\nWhen my way grows drear,\nPrecious Lord, linger near,\nWhen my life is almost gone,\nHear my cry, hear my call,\nHold my hand lest I fall:\n\nRefrain\n\nWhen the darkness appears\nAnd the night draws near,\nAnd the day is past and gone,\nAt the river I stand,\nGuide my feet, hold my hand:\n\nRefrain\n\n \n',
  'RESCUE THE PERISHING':
      'Rescue the perishing, care for the dying,\nSnatch them in pity from sin and the grave;\nWeep o’er the erring one, lift up the fallen,\nTell them of Jesus, the mighty to save.\n\nRefrain\n\nRescue the perishing, care for the dying,\nJesus is merciful, Jesus will save.\n\nThough they are slighting Him, still He is waiting,\nWaiting the penitent child to receive;\nPlead with them earnestly, plead with them gently;\nHe will forgive if they only believe.\n\nRefrain\n\nDown in the human heart, crushed by the tempter,\nFeelings lie buried that grace can restore;\nTouched by a loving heart, wakened by kindness,\nChords that were broken will vibrate once more.\n\nRefrain\n\nRescue the perishing, duty demands it;\nStrength for thy labor the Lord will provide;\nBack to the narrow way patiently win them;\nTell the poor wand’rer a Savior has died.\n\nRefrain\n\n \n',
  'REVIVE US AGAIN':
      'We praise Thee, O God!\nFor the Son of Thy love,\nFor Jesus Who died,\nAnd is now gone above.\nRefrain\n\nHallelujah! Thine the glory.\nHallelujah! Amen.\nHallelujah! Thine the glory.\nRevive us again.\n\nWe praise Thee, O God!\nFor Thy Spirit of light,\nWho hath shown us our Savior,\nAnd scattered our night.\n\nRefrain\n\nAll glory and praise\nTo the Lamb that was slain,\nWho hath borne all our sins,\nAnd hath cleansed every stain.\n\nRefrain\n\nAll glory and praise\nTo the God of all grace,\nWho hast brought us, and sought us,\nAnd guided our ways.\n\nRefrain\n\nRevive us again;\nFill each heart with Thy love;\nMay each soul be rekindled\nWith fire from above.\n\nRefrain\n\n \n \n',
  'ROCK OF AGES':
      'Rock of Ages, cleft for me,\nLet me hide myself in Thee;\nLet the water and the blood,\nFrom Thy riven side which flowed,\nBe of sin the double cure,\nCleanse me from its guilt and pow’r.\n\nNot the labors of my hands\nCan fulfill Thy law’s demands;\nCould my zeal no respite know,\nCould my tears forever flow,\nAll for sin could not atone:\nThou must save, and Thou alone.\n\nNothing in my hand I bring,\nSimply to Thy cross I cling;\nNaked, come to Thee for dress;\nHelpless, look to Thee for grace;\nFoul, I to the fountain fly;\nWash me, Saviour, or I die.\n\nWhile I draw this fleeting breath,\nWhen my eyelids close in death,\nWhen I soar to worlds unknown,\nSee Thee on Thy judgment throne;\nRock of Ages, cleft for me,\nLet me hide myself in Thee.\n\nThen above the world and sin,\nThro’ the veil, drawn right within,\nI shall see Him face to face,\nSing the story, saved by grace,\nRock of Ages, cleft for me,\nLet me ever be with Thee.\n\n',
  'SAFE IN THE ARMS OF JESUS':
      'Safe in the arms of Jesus, safe on His gentle breast,\nThere by His love o’ershaded, sweetly my soul shall rest.\nHark! ’tis the voice of angels, borne in a song to me.\nOver the fields of glory, over the jasper sea.\nRefrain\n\nSafe in the arms of Jesus, safe on His gentle breast\nThere by His love o’ershaded, sweetly my soul shall rest.\n\nSafe in the arms of Jesus, safe from corroding care,\nSafe from the world’s temptations, sin cannot harm me there.\nFree from the blight of sorrow, free from my doubts and fears;\nOnly a few more trials, only a few more tears!\n\nRefrain\n\nJesus, my heart’s dear Refuge, Jesus has died for me;\nFirm on the Rock of Ages, ever my trust shall be.\nHere let me wait with patience, wait till the night is over;\nWait till I see the morning break on the golden shore.\n\nRefrain\n\n \n',
  'SAVIOUR LIKE A SHEPHERD LEAD US':
      'Saviour, like a shepherd lead us,\nMuch we need Thy tender care;\nIn Thy pleasant pastures feed us,\nFor our use Thy folds prepare:\nBlessed Jesus, Blessed Jesus,\nThou hast bought us, Thine we are;\nBlessed Jesus, Blessed Jesus,\nThou hast bought us, Thine we are.\n\nWe are Thine; do Thou befriend us,\nBe the Guardian of our way;\nKeep Thy flock, from sin defend us,\nSeek us when we go astray:\nBlessed Jesus, Blessed Jesus,\nHear, O hear us when we pray;\nBlessed Jesus, Blessed Jesus,\nHear, O hear us when we pray.\n\nThou hast promised to receive us,\nPoor and sinful tho’ we be;\nThou hast mercy to relieve us,\nGrace to cleanse, and pow’r to free:\nBlessed Jesus, Blessed Jesus,\nEarly let us turn to Thee;\nBlessed Jesus, Blessed Jesus,\nEarly let us turn to Thee.\n\nEarly let us seek Thy favor;\nEarly let us do Thy will;\nBlessed Lord and only Saviour,\nWith Thy love our bosoms fill:\nBlessed Jesus, Blessed Jesus,\nThou hast loved us, love us still;\nBlessed Jesus, Blessed Jesus,\nThou hast loved us, love us still.\n\n\n',
  'SOFTLY AND TENDERLY JESUS IS CALLING':
      'Softly and tenderly Jesus is calling,\nCalling for you and for me;\nSee, on the portals He’s waiting and watching,\nWatching for you and for me.\nRefrain\n\nCome home, come home,\nYou who are weary, come home;\nEarnestly, tenderly, Jesus is calling,\nCalling, O sinner, come home!\n\nWhy should we tarry when Jesus is pleading,\nPleading for you and for me?\nWhy should we linger and heed not His mercies,\nMercies for you and for me?\n\nRefrain\n\nTime is now fleeting, the moments are passing,\nPassing from you and from me;\nShadows are gathering, deathbeds are coming,\nComing for you and for me.\n\nRefrain\n\nO for the wonderful love He has promised,\nPromised for you and for me!\nThough we have sinned, He has mercy and pardon,\nPardon for you and for me.\n\nRefrain\n\n \n',
  'STANDING ON THE PROMISES':
      'Standing on the promises of Christ my King,\nThrough eternal ages let His praises ring,\nGlory in the highest, I will shout and sing,\nStanding on the promises of God.\n\nRefrain\n\nStanding, standing,\nStanding on the promises of God my Savior;\nStanding, standing,\nI’m standing on the promises of God.\n\nStanding on the promises that cannot fail,\nWhen the howling storms of doubt and fear assail,\nBy the living Word of God I shall prevail,\nStanding on the promises of God.\n\nRefrain\n\nStanding on the promises I now can see\nPerfect, present cleansing in the blood for me;\nStanding in the liberty where Christ makes free,\nStanding on the promises of God.\n\nRefrain\n\nStanding on the promises of Christ the Lord,\nBound to Him eternally by love’s strong cord,\nOvercoming daily with the Spirit’s sword,\nStanding on the promises of God.\n\nRefrain\n\nStanding on the promises I cannot fall,\nListening every moment to the Spirit’s call\nResting in my Savior as my all in all,\nStanding on the promises of God.\n\nRefrain\n\n',
  'TAKE MY LIFE AND LET IT BE':
      'Verse 1:\nTake my life, and let it be\nConsecrated, Lord, to Thee;\nTake my moments and my days,\nLet them flow in ceaseless praise.\nLet them flow in ceaseless praise.\n\n\nVerse 2:\nTake my hands, and let them move\nAt the impulse of Thy love;\nTake my feet, and let them be\nSwift and beautiful for Thee.\nSwift and beautiful for Thee.\n\n\nVerse 3:\nTake my voice, and let me sing\nAlways, only, for my King;\nTake my lips, and let them be\nFilled with messages from Thee.\nFilled with messages from Thee.\n\n\nVerse 4:\nTake my silver and my gold:\nNot a mite would I withhold;\nTake my intellect, and use\nEv’ry pow’r as Thou shalt choose.\nEv’ry pow’r as Thou shalt choose.\n\n\nVerse 5:\nTake my will, and make it Thine,\nIt shall be no longer mine;\nTake my heart, it is Thine own,\nIt shall be Thy royal throne.\nIt shall be Thy royal throne.\n\n\nVerse 6:\nTake my love, my Lord, I pour\nAt Thy feet its treasure store;\nTake myself, and I will be,\nEver, only, all for Thee.\nEver, only, all for Thee.\n \n',
  'TAKE TIME TO BE HOLY':
      'Take time to be holy, speak oft with thy Lord;\nAbide in Him always, and feed on His Word.\nMake friends of God’s children, help those who are weak,\nForgetting in nothing His blessing to seek.\n\nTake time to be holy, the world rushes on;\nSpend much time in secret, with Jesus alone.\nBy looking to Jesus, like Him thou shalt be;\nThy friends in thy conduct His likeness shall see.\n\nTake time to be holy, let Him be thy Guide;\nAnd run not before Him, whatever betide.\nIn joy or in sorrow, still follow the Lord,\nAnd, looking to Jesus, still trust in His Word.\n\nTake time to be holy, be calm in thy soul,\nEach thought and each motive beneath His control.\nThus led by His Spirit to fountains of love,\nThou soon shalt be fitted for service above.\n\n \n',
  'THE OLD RUGGED CROSS':
      'On a hill far away stood an old rugged cross,\nThe emblem of suffering and shame;\nAnd I love that old cross where the dearest and best\nFor a world of lost sinners was slain.\n\nRefrain\n\nSo I’ll cherish the old rugged cross,\nTill my trophies at last I lay down;\nI will cling to the old rugged cross,\nAnd exchange it some day for a crown.\n\nO that old rugged cross, so despised by the world,\nHas a wondrous attraction for me;\nFor the dear Lamb of God left His glory above\nTo bear it to dark Calvary.\n\nRefrain\n\nIn that old rugged cross, stained with blood so divine,\nA wondrous beauty I see,\nFor ’twas on that old cross Jesus suffered and died,\nTo pardon and sanctify me.\n\nRefrain\n\nTo the old rugged cross I will ever be true;\nIts shame and reproach gladly bear;\nThen He’ll call me some day to my home far away,\nWhere His glory forever I’ll share.\n\nRefrain\n\n \n',
  'THERE IS A FOUNTAIN':
      'There is a fountain filled with blood drawn from Emmanuel’s veins;\nAnd sinners plunged beneath that flood lose all their guilty stains.\nLose all their guilty stains, lose all their guilty stains;\nAnd sinners plunged beneath that flood lose all their guilty stains.\nThe dying thief rejoiced to see that fountain in his day;\nAnd there have I, though vile as he, washed all my sins away.\nWashed all my sins away, washed all my sins away;\nAnd there have I, though vile as he, washed all my sins away.\n\nDear dying Lamb, Thy precious blood shall never lose its power\nTill all the ransomed church of God be saved, to sin no more.\nBe saved, to sin no more, be saved, to sin no more;\nTill all the ransomed church of God be saved, to sin no more.\n\nE’er since, by faith, I saw the stream Thy flowing wounds supply,\nRedeeming love has been my theme, and shall be till I die.\nAnd shall be till I die, and shall be till I die;\nRedeeming love has been my theme, and shall be till I die.\n\nThen in a nobler, sweeter song, I’ll sing Thy power to save,\nWhen this poor lisping, stammering tongue lies silent in the grave.\nLies silent in the grave, lies silent in the grave;\nWhen this poor lisping, stammering tongue lies silent in the grave.\n\nLord, I believe Thou hast prepared, unworthy though I be,\nFor me a blood bought free reward, a golden harp for me!\n’Tis strung and tuned for endless years, and formed by power divine,\nTo sound in God the Father’s ears no other name but Thine.\n\n \n',
  'THERE IS POWER IN THE BLOOD':
      'Would you be free from the burden of sin?\nThere’s power in the blood, power in the blood;\nWould you o’er evil a victory win?\nThere’s wonderful power in the blood.\nRefrain\n\nThere is power, power, wonder working power\nIn the blood of the Lamb;\nThere is power, power, wonder working power\nIn the precious blood of the Lamb.\n\nWould you be free from your passion and pride?\nThere’s power in the blood, power in the blood;\nCome for a cleansing to Calvary’s tide;\nThere’s wonderful power in the blood.\n\nRefrain\n\nWould you be whiter, much whiter than snow?\nThere’s power in the blood, power in the blood;\nSin stains are lost in its life giving flow.\nThere’s wonderful power in the blood.\n\nRefrain\n\nWould you do service for Jesus your King?\nThere’s power in the blood, power in the blood;\nWould you live daily His praises to sing?\nThere’s wonderful power in the blood.\n\nRefrain\n\n \n',
  'TILL THE STORM PASSES BY':
      'In the dark of the midnight,\nHave I oft hid my face;\nWhile the storm howls above me,\nAnd there’s no hiding place;\n’Mid the crash of the thunder,\nPrecious Lord, hear my cry;\n"Keep me safe ’til the storm passes by."\n\n’Til the storm passes over,\n’Til the thunder sounds no more;\n’Til the clouds roll forever from the sky,\nHold me fast, let me stand,\nIn the hollow of Thy hand;\nKeep me safe ’til the storm passes by.\n\nMany times Satan whispers,\n"There is no need to try;\nFor there’s no end of sorrow,\nThere’s no hope by and by";\nBut I know Thou art with me,\nAnd tomorrow I’ll rise;\nWhere the storms never darken the skies.\n\n’Til the storm passes over,\n’Til the thunder sounds no more;\n’Til the clouds roll forever from the sky,\nHold me fast, let me stand,\nIn the hollow of Thy hand;\nKeep me safe ’til the storm passes by.\n\nWhen the long night has ended,\nAnd the storms come no more,\nLet me stand in Thy presence.\nOn that bright, peaceful shore.\nIn that land where the tempest\nNever comes, Lord may I\nDwell with Thee when the storm passes by.\n\n’Til the storm passes over,\n’Til the thunder sounds no more;\n’Til the clouds roll forever from the sky,\nHold me fast, let me stand,\nIn the hollow of Thy hand;\nKeep me safe ’til the storm passes by.\n\nHold me fast, Let me stand,\nIn the hollow of Thy hand;\nKeep me safe ’til the storm passes by.\n\n’Til the storm passes by.\n \n',
  'TURN YOUR EYES UPON JESUS':
      'O soul, are you weary and troubled?\nNo light in the darkness you see?\nThere’s a light for a look at the Savior,\nAnd life more abundant and free!\n\nRefrain\n\nTurn your eyes upon Jesus,\nLook full in His wonderful face,\nAnd the things of earth will grow strangely dim,\nIn the light of His glory and grace.\n\nThrough death into life everlasting\nHe passed, and we follow Him there;\nOver us sin no more hath dominion—\nFor more than conquerors we are!\n\nRefrain\n\nHis Word shall not fail you—He promised;\nBelieve Him, and all will be well:\nThen go to a world that is dying,\nHis perfect salvation to tell!\n\nRefrain\n\n \n',
  'TRUST AND OBEY':
      'When we walk with the Lord in the light of His Word,\nWhat a glory He sheds on our way!\nWhile we do His good will, He abides with us still,\nAnd with all who will trust and obey.\n\nRefrain\n\nTrust and obey, for there’s no other way\nTo be happy in Jesus, but to trust and obey.\n\nNot a shadow can rise, not a cloud in the skies,\nBut His smile quickly drives it away;\nNot a doubt or a fear, not a sigh or a tear,\nCan abide while we trust and obey.\n\nRefrain\n\nNot a burden we bear, not a sorrow we share,\nBut our toil He doth richly repay;\nNot a grief or a loss, not a frown or a cross,\nBut is blessed if we trust and obey.\n\nRefrain\n\nBut we never can prove the delights of His love\nUntil all on the altar we lay;\nFor the favor He shows, for the joy He bestows,\nAre for them who will trust and obey.\n\nRefrain\n\nThen in fellowship sweet we will sit at His feet.\nOr we’ll walk by His side in the way.\nWhat He says we will do, where He sends we will go;\nNever fear, only trust and obey.\n\nRefrain\n\n \n',
  'VICTORY IN JESUS':
      'I heard an old, old story,\nHow a Savior came from glory,\nHow He gave His life on Calvary\nTo save a wretch like me;\nI heard about His groaning,\nOf His precious blood’s atoning,\nThen I repented of my sins\nAnd won the victory.\n\n\nChorus\nO victory in Jesus,\nMy Savior, forever.\nHe sought me and bought me\nWith His redeeming blood;\nHe loved me ere I knew Him\nAnd all my love is due Him,\nHe plunged me to victory,\nBeneath the cleansing flood.\n\nI heard about His healing,\nOf His cleansing pow’r revealing.\nHow He made the lame to walk again\nAnd caused the blind to see;\nAnd then I cried, "Dear Jesus,\nCome and heal my broken spirit,"\nAnd somehow Jesus came and bro’t\nTo me the victory.\n\n\nI heard about a mansion\nHe has built for me in glory.\nAnd I heard about the streets of gold\nBeyond the crystal sea;\nAbout the angels singing,\nAnd the old redemption story,\nAnd some sweet day I’ll sing up there\nThe song of victory.\n\n\n',
  'WHAT DAY THAT WILL BE':
      'There is coming a day when no heartaches shall come\nNo more clouds in the sky, no more tears to dim the eye.\nAll is peace forevermore on that happy golden shore,\nWhat a day, glorious day that will be.\n\nChorus\nWhat a day that will be when my Jesus I shall see,\nAnd I look upon His face,\nThe One who saved me by His grace;\nWhen He takes me by the hand\nAnd leads me through the Promised Land,\nWhat a day, glorious day that will be.\n\nThere’ll be no sorrow there, no more burdens to bear,\nNo more sickness, no pain, no more parting over there;\nAnd forever I will be with the One who died for me,\nWhat a day, glorious day that will be.\n\n\nChorus\nWhat a day that will be when my Jesus I shall see,\nAnd I look upon His face,\nThe One who saved me by His grace;\nWhen He takes me by the hand\nAnd leads me through the Promised Land,\nWhat a day, glorious day that will be.\nWhat a day, glorious day that will be!\n \n',
  'WHAT A FRIEND WE HAVE IN JESUS':
      'What a Friend we have in Jesus, all our sins and griefs to bear!\nWhat a privilege to carry everything to God in prayer!\nO what peace we often forfeit, O what needless pain we bear,\nAll because we do not carry everything to God in prayer.\n\n\nHave we trials and temptations? Is there trouble anywhere?\nWe should never be discouraged; take it to the Lord in prayer.\nCan we find a friend so faithful who will all our sorrows share?\nJesus knows our every weakness; take it to the Lord in prayer.\n\n\nAre we weak and heavy laden, cumbered with a load of care?\nPrecious Savior, still our refuge, take it to the Lord in prayer.\nDo your friends despise, forsake you? Take it to the Lord in prayer!\nIn His arms He’ll take and shield you; you will find a solace there.\n\n\nBlessed Savior, Thou hast promised Thou wilt all our burdens bear\nMay we ever, Lord, be bringing all to Thee in earnest prayer.\nSoon in glory bright unclouded there will be no need for prayer\nRapture, praise and endless worship will be our sweet portion there.\n\n \n',
  'WHAT CHILD IS THIS?':
      'What Child is this who, laid to rest\nOn Mary’s lap is sleeping?\nWhom angels greet with anthems sweet,\nWhile shepherds watch are keeping?\nThis, this is Christ the King,\nWhom shepherds guard and angels sing;\nHaste, haste, to bring Him laud,\nThe Babe, the Son of Mary.\nWhy lies He in such mean estate,\nWhere ox and ass are feeding?\nGood Christians, fear, for sinners here\nThe silent Word is pleading.\nNails, spear shall pierce Him through,\nThe cross be borne for me, for you.\nHail, hail the Word made flesh,\nThe Babe, the Son of Mary.\n\nSo bring Him incense, gold and myrrh,\nCome peasant, king to own Him;\nThe King of kings salvation brings,\nLet loving hearts enthrone Him.\nRaise, raise a song on high,\nThe virgin sings her lullaby.\nJoy, joy for Christ is born,\nThe Babe, the Son of Mary.\n\n \n',
  'WHEN I SURVEY THE WONDROUS CROSS':
      'When I survey the wondrous cross\nOn which the Prince of glory died,\nMy richest gain I count but loss,\nAnd pour contempt on all my pride.\n\nForbid it, Lord, that I should boast,\nSave in the death of Christ my God!\nAll the vain things that charm me most,\nI sacrifice them to His blood.\n\nSee from His head, His hands, His feet,\nSorrow and love flow mingled down!\nDid e’er such love and sorrow meet,\nOr thorns compose so rich a crown?\n\nHis dying crimson, like a robe,\nSpreads o’er His body on the tree;\nThen I am dead to all the globe,\nAnd all the globe is dead to me.\n\nWere the whole realm of nature mine,\nThat were a present far too small;\nLove so amazing, so divine,\nDemands my soul, my life, my all.\n\n\n',
  'WHEN THE ROLL IS CALLED UP YONDER':
      'When the trumpet of the Lord shall sound, and time shall be no more,\nAnd the morning breaks, eternal, bright and fair;\nWhen the saved of earth shall gather over on the other shore,\nAnd the roll is called up yonder, I’ll be there.\n\nRefrain\n\nWhen the roll, is called up yonder,\nWhen the roll, is called up yonder,\nWhen the roll, is called up yonder,\nWhen the roll is called up yonder I’ll be there.\n\nOn that bright and cloudless morning when the dead in Christ shall rise,\nAnd the glory of His resurrection share;\nWhen His chosen ones shall gather to their home beyond the skies,\nAnd the roll is called up yonder, I’ll be there.\n\nRefrain\n\nLet us labor for the Master from the dawn till setting sun,\nLet us talk of all His wondrous love and care;\nThen when all of life is over, and our work on earth is done,\nAnd the roll is called up yonder, I’ll be there.\n\nRefrain\n\n\n',
  'WHEN WE ALL GET TO HEAVEN':
      'Sing the wondrous love of Jesus,\nSing His mercy and His grace.\nIn the mansions bright and blessèd\nHe’ll prepare for us a place.\nRefrain\n\nWhen we all get to Heaven,\nWhat a day of rejoicing that will be!\nWhen we all see Jesus,\nWe’ll sing and shout the victory!\n\nWhile we walk the pilgrim pathway,\nClouds will overspread the sky;\nBut when traveling days are over,\nNot a shadow, not a sigh.\n\nRefrain\n\nLet us then be true and faithful,\nTrusting, serving every day;\nJust one glimpse of Him in glory\nWill the toils of life repay.\n\nRefrain\n\nOnward to the prize before us!\nSoon His beauty we’ll behold;\nSoon the pearly gates will open;\nWe shall tread the streets of gold.\n\nRefrain\n\n\n',
  'WHEREVER HE LEADS I’LL GO':
      '“Take up thy cross and follow me,”\nI heard my Master say;\n“I gave me life to ransom thee,\nSurrender your all today.”\n\nCHORUS:\nWherever He leads I’ll go,\nWherever He leads I’ll go,\nI’ll follow my Christ who loves me so,\nWherever He leads I’ll go.\n\nHe drew me closer to His side,\nI sought His will to know,\nAnd in that will I now abide,\nWherever He leads I’ll go.\n\nIt may be through the shadows dim,\nOr o’er the stormy sea,\nI take my cross and follow Him,\nWherever He leadeth me.\n\n \n',
  'YESTERDAY, TODAY, FOREVER':
      'O how sweet the glorious message simple faith may claim\nYesterday, today, forever Jesus is the same.\nStill He loves to save the sinful, heal the sick and lame\nCheer the mourner, still the tempest, glory to His Name.\nRefrain\n\nYesterday, today, forever, Jesus is the same.\nAll may change, but Jesus never! Glory to His Name!\nGlory to His Name! Glory to His Name!\nAll may change, but Jesus never! Glory to His Name!\n\nHe, who was the Friend of sinners, seeks the lost one now\nSinner come, and at His footstool penitently bow\nHe Who said “I’ll not condemn thee, go and sin no more,”\nSpeaks to thee that word of pardon as in days of yore.\n\nRefrain\n\nOft on earth He healed the sufferer by His mighty hand\nStill our sicknesses and sorrows go at His command\nHe who gave His healing virtue to a woman’s touch\nTo the faith that claims His fullness still will give as much.\n\nRefrain\n\nAs of old He walked to Emmaus, with them to abide\nSo through all life’s way He walketh ever near our side\nSoon again we shall behold Him, Hasten Lord the day\nBut twill still be this same Jesus as He went away.\n\nRefrain\n\n'
};
